// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mt5-term-api-vnc.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VncData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *VncData) Reset() {
	*x = VncData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_vnc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VncData) ProtoMessage() {}

func (x *VncData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_vnc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VncData.ProtoReflect.Descriptor instead.
func (*VncData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_vnc_proto_rawDescGZIP(), []int{0}
}

func (x *VncData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_mt5_term_api_vnc_proto protoreflect.FileDescriptor

var file_mt5_term_api_vnc_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x74, 0x35, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x76,
	0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x23, 0x0a, 0x07, 0x56, 0x6e, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x4b, 0x0a, 0x0a, 0x56,
	0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x56, 0x6e, 0x63,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x15, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x15, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6e, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x28, 0x01, 0x30, 0x01, 0x42, 0x42, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x2e,
	0x6d, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x6d, 0x72,
	0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x6d, 0x74, 0x35,
	0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0xaa, 0x02, 0x0c,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mt5_term_api_vnc_proto_rawDescOnce sync.Once
	file_mt5_term_api_vnc_proto_rawDescData = file_mt5_term_api_vnc_proto_rawDesc
)

func file_mt5_term_api_vnc_proto_rawDescGZIP() []byte {
	file_mt5_term_api_vnc_proto_rawDescOnce.Do(func() {
		file_mt5_term_api_vnc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt5_term_api_vnc_proto_rawDescData)
	})
	return file_mt5_term_api_vnc_proto_rawDescData
}

var file_mt5_term_api_vnc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mt5_term_api_vnc_proto_goTypes = []interface{}{
	(*VncData)(nil), // 0: mt5_term_api.VncData
}
var file_mt5_term_api_vnc_proto_depIdxs = []int32{
	0, // 0: mt5_term_api.VncService.VncStream:input_type -> mt5_term_api.VncData
	0, // 1: mt5_term_api.VncService.VncStream:output_type -> mt5_term_api.VncData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mt5_term_api_vnc_proto_init() }
func file_mt5_term_api_vnc_proto_init() {
	if File_mt5_term_api_vnc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mt5_term_api_vnc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VncData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt5_term_api_vnc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt5_term_api_vnc_proto_goTypes,
		DependencyIndexes: file_mt5_term_api_vnc_proto_depIdxs,
		MessageInfos:      file_mt5_term_api_vnc_proto_msgTypes,
	}.Build()
	File_mt5_term_api_vnc_proto = out.File
	file_mt5_term_api_vnc_proto_rawDesc = nil
	file_mt5_term_api_vnc_proto_goTypes = nil
	file_mt5_term_api_vnc_proto_depIdxs = nil
}
