// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-demo-account.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemoAccountClient is the client API for DemoAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoAccountClient interface {
	// Search for broker companies by name.
	// Returns a list of matching companies from the wizard's ListView.
	// [DefaultValues]
	//
	//	{
	//	  "searchText": "MetaQuotes"
	//	}
	FindCompanies(ctx context.Context, in *GuiDemoFindCompaniesRequest, opts ...grpc.CallOption) (*GuiDemoFindCompaniesReply, error)
	// Get available servers and account types for a company.
	// Navigates: company selection → demo account → reads dropdown options.
	// [DefaultValues]
	//
	//	{
	//	  "companyName": "MetaQuotes Ltd."
	//	}
	ServersAndAccountTypes(ctx context.Context, in *GuiDemoServersAndTypesRequest, opts ...grpc.CallOption) (*GuiDemoServersAndTypesReply, error)
	// Open a demo account. Full wizard flow: search → select → fill form → register.
	// Returns login, password, and investor password for the new demo account.
	// [DefaultValues]
	//
	//	{
	//	  "company": "MetaQuotes Ltd.",
	//	  "firstName": "Test",
	//	  "lastName": "User",
	//	  "email": "test@test.com",
	//	  "phone": "+1234567890",
	//	  "timeoutSeconds": "60"
	//	}
	OpenDemoAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error)
	// Same as OpenDemoAccount but streams real-time progress events.
	// Does NOT require 'id' header — auto-picks any available terminal.
	// Swagger does not support streaming — use /demo-account-stream interactive viewer.
	// [DefaultValues]
	//
	//	{
	//	  "company": "MetaQuotes Ltd.",
	//	  "firstName": "Test",
	//	  "lastName": "User",
	//	  "email": "test@test.com",
	//	  "phone": "+1234567890",
	//	  "timeoutSeconds": "60"
	//	}
	OpenDemoAccountStream(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (DemoAccount_OpenDemoAccountStreamClient, error)
}

type demoAccountClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoAccountClient(cc grpc.ClientConnInterface) DemoAccountClient {
	return &demoAccountClient{cc}
}

func (c *demoAccountClient) FindCompanies(ctx context.Context, in *GuiDemoFindCompaniesRequest, opts ...grpc.CallOption) (*GuiDemoFindCompaniesReply, error) {
	out := new(GuiDemoFindCompaniesReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.DemoAccount/FindCompanies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoAccountClient) ServersAndAccountTypes(ctx context.Context, in *GuiDemoServersAndTypesRequest, opts ...grpc.CallOption) (*GuiDemoServersAndTypesReply, error) {
	out := new(GuiDemoServersAndTypesReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.DemoAccount/ServersAndAccountTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoAccountClient) OpenDemoAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error) {
	out := new(GuiDemoOpenAccountReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.DemoAccount/OpenDemoAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoAccountClient) OpenDemoAccountStream(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (DemoAccount_OpenDemoAccountStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoAccount_ServiceDesc.Streams[0], "/mt5_term_api.DemoAccount/OpenDemoAccountStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoAccountOpenDemoAccountStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DemoAccount_OpenDemoAccountStreamClient interface {
	Recv() (*DemoAccountStreamEvent, error)
	grpc.ClientStream
}

type demoAccountOpenDemoAccountStreamClient struct {
	grpc.ClientStream
}

func (x *demoAccountOpenDemoAccountStreamClient) Recv() (*DemoAccountStreamEvent, error) {
	m := new(DemoAccountStreamEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoAccountServer is the server API for DemoAccount service.
// All implementations should embed UnimplementedDemoAccountServer
// for forward compatibility
type DemoAccountServer interface {
	// Search for broker companies by name.
	// Returns a list of matching companies from the wizard's ListView.
	// [DefaultValues]
	//
	//	{
	//	  "searchText": "MetaQuotes"
	//	}
	FindCompanies(context.Context, *GuiDemoFindCompaniesRequest) (*GuiDemoFindCompaniesReply, error)
	// Get available servers and account types for a company.
	// Navigates: company selection → demo account → reads dropdown options.
	// [DefaultValues]
	//
	//	{
	//	  "companyName": "MetaQuotes Ltd."
	//	}
	ServersAndAccountTypes(context.Context, *GuiDemoServersAndTypesRequest) (*GuiDemoServersAndTypesReply, error)
	// Open a demo account. Full wizard flow: search → select → fill form → register.
	// Returns login, password, and investor password for the new demo account.
	// [DefaultValues]
	//
	//	{
	//	  "company": "MetaQuotes Ltd.",
	//	  "firstName": "Test",
	//	  "lastName": "User",
	//	  "email": "test@test.com",
	//	  "phone": "+1234567890",
	//	  "timeoutSeconds": "60"
	//	}
	OpenDemoAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error)
	// Same as OpenDemoAccount but streams real-time progress events.
	// Does NOT require 'id' header — auto-picks any available terminal.
	// Swagger does not support streaming — use /demo-account-stream interactive viewer.
	// [DefaultValues]
	//
	//	{
	//	  "company": "MetaQuotes Ltd.",
	//	  "firstName": "Test",
	//	  "lastName": "User",
	//	  "email": "test@test.com",
	//	  "phone": "+1234567890",
	//	  "timeoutSeconds": "60"
	//	}
	OpenDemoAccountStream(*GuiDemoOpenAccountRequest, DemoAccount_OpenDemoAccountStreamServer) error
}

// UnimplementedDemoAccountServer should be embedded to have forward compatible implementations.
type UnimplementedDemoAccountServer struct {
}

func (UnimplementedDemoAccountServer) FindCompanies(context.Context, *GuiDemoFindCompaniesRequest) (*GuiDemoFindCompaniesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCompanies not implemented")
}
func (UnimplementedDemoAccountServer) ServersAndAccountTypes(context.Context, *GuiDemoServersAndTypesRequest) (*GuiDemoServersAndTypesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServersAndAccountTypes not implemented")
}
func (UnimplementedDemoAccountServer) OpenDemoAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenDemoAccount not implemented")
}
func (UnimplementedDemoAccountServer) OpenDemoAccountStream(*GuiDemoOpenAccountRequest, DemoAccount_OpenDemoAccountStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenDemoAccountStream not implemented")
}

// UnsafeDemoAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoAccountServer will
// result in compilation errors.
type UnsafeDemoAccountServer interface {
	mustEmbedUnimplementedDemoAccountServer()
}

func RegisterDemoAccountServer(s grpc.ServiceRegistrar, srv DemoAccountServer) {
	s.RegisterService(&DemoAccount_ServiceDesc, srv)
}

func _DemoAccount_FindCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoFindCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoAccountServer).FindCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.DemoAccount/FindCompanies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoAccountServer).FindCompanies(ctx, req.(*GuiDemoFindCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoAccount_ServersAndAccountTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoServersAndTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoAccountServer).ServersAndAccountTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.DemoAccount/ServersAndAccountTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoAccountServer).ServersAndAccountTypes(ctx, req.(*GuiDemoServersAndTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoAccount_OpenDemoAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoOpenAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoAccountServer).OpenDemoAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.DemoAccount/OpenDemoAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoAccountServer).OpenDemoAccount(ctx, req.(*GuiDemoOpenAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoAccount_OpenDemoAccountStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GuiDemoOpenAccountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoAccountServer).OpenDemoAccountStream(m, &demoAccountOpenDemoAccountStreamServer{stream})
}

type DemoAccount_OpenDemoAccountStreamServer interface {
	Send(*DemoAccountStreamEvent) error
	grpc.ServerStream
}

type demoAccountOpenDemoAccountStreamServer struct {
	grpc.ServerStream
}

func (x *demoAccountOpenDemoAccountStreamServer) Send(m *DemoAccountStreamEvent) error {
	return x.ServerStream.SendMsg(m)
}

// DemoAccount_ServiceDesc is the grpc.ServiceDesc for DemoAccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoAccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.DemoAccount",
	HandlerType: (*DemoAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindCompanies",
			Handler:    _DemoAccount_FindCompanies_Handler,
		},
		{
			MethodName: "ServersAndAccountTypes",
			Handler:    _DemoAccount_ServersAndAccountTypes_Handler,
		},
		{
			MethodName: "OpenDemoAccount",
			Handler:    _DemoAccount_OpenDemoAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenDemoAccountStream",
			Handler:       _DemoAccount_OpenDemoAccountStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mt5-term-api-demo-account.proto",
}
