// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-trading-helper.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradingHelperClient is the client API for TradingHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradingHelperClient interface {
	// Send market or pending order
	OrderSend(ctx context.Context, in *OrderSendRequest, opts ...grpc.CallOption) (*OrderSendReply, error)
	// Modify market or pending order
	OrderModify(ctx context.Context, in *OrderModifyRequest, opts ...grpc.CallOption) (*OrderModifyReply, error)
	// Close market or pending order
	OrderClose(ctx context.Context, in *OrderCloseRequest, opts ...grpc.CallOption) (*OrderCloseReply, error)
}

type tradingHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingHelperClient(cc grpc.ClientConnInterface) TradingHelperClient {
	return &tradingHelperClient{cc}
}

func (c *tradingHelperClient) OrderSend(ctx context.Context, in *OrderSendRequest, opts ...grpc.CallOption) (*OrderSendReply, error) {
	out := new(OrderSendReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradingHelper/OrderSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingHelperClient) OrderModify(ctx context.Context, in *OrderModifyRequest, opts ...grpc.CallOption) (*OrderModifyReply, error) {
	out := new(OrderModifyReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradingHelper/OrderModify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingHelperClient) OrderClose(ctx context.Context, in *OrderCloseRequest, opts ...grpc.CallOption) (*OrderCloseReply, error) {
	out := new(OrderCloseReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradingHelper/OrderClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingHelperServer is the server API for TradingHelper service.
// All implementations should embed UnimplementedTradingHelperServer
// for forward compatibility
type TradingHelperServer interface {
	// Send market or pending order
	OrderSend(context.Context, *OrderSendRequest) (*OrderSendReply, error)
	// Modify market or pending order
	OrderModify(context.Context, *OrderModifyRequest) (*OrderModifyReply, error)
	// Close market or pending order
	OrderClose(context.Context, *OrderCloseRequest) (*OrderCloseReply, error)
}

// UnimplementedTradingHelperServer should be embedded to have forward compatible implementations.
type UnimplementedTradingHelperServer struct {
}

func (UnimplementedTradingHelperServer) OrderSend(context.Context, *OrderSendRequest) (*OrderSendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderSend not implemented")
}
func (UnimplementedTradingHelperServer) OrderModify(context.Context, *OrderModifyRequest) (*OrderModifyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderModify not implemented")
}
func (UnimplementedTradingHelperServer) OrderClose(context.Context, *OrderCloseRequest) (*OrderCloseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderClose not implemented")
}

// UnsafeTradingHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingHelperServer will
// result in compilation errors.
type UnsafeTradingHelperServer interface {
	mustEmbedUnimplementedTradingHelperServer()
}

func RegisterTradingHelperServer(s grpc.ServiceRegistrar, srv TradingHelperServer) {
	s.RegisterService(&TradingHelper_ServiceDesc, srv)
}

func _TradingHelper_OrderSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingHelperServer).OrderSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradingHelper/OrderSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingHelperServer).OrderSend(ctx, req.(*OrderSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingHelper_OrderModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingHelperServer).OrderModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradingHelper/OrderModify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingHelperServer).OrderModify(ctx, req.(*OrderModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingHelper_OrderClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingHelperServer).OrderClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradingHelper/OrderClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingHelperServer).OrderClose(ctx, req.(*OrderCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradingHelper_ServiceDesc is the grpc.ServiceDesc for TradingHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradingHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.TradingHelper",
	HandlerType: (*TradingHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderSend",
			Handler:    _TradingHelper_OrderSend_Handler,
		},
		{
			MethodName: "OrderModify",
			Handler:    _TradingHelper_OrderModify_Handler,
		},
		{
			MethodName: "OrderClose",
			Handler:    _TradingHelper_OrderClose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-trading-helper.proto",
}
