// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-admin.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminApiClient is the client API for AdminApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminApiClient interface {
	// Active terminals running on THIS pod.
	ActiveTerminals(ctx context.Context, in *ActiveTerminalsRequest, opts ...grpc.CallOption) (*ActiveTerminalsReply, error)
	// Active terminals across ALL pods of this StatefulSet/Deployment.
	// Lists peer pods via the Kubernetes API, then calls ActiveTerminals on each.
	ActiveTerminalsCluster(ctx context.Context, in *ActiveTerminalsRequest, opts ...grpc.CallOption) (*ActiveTerminalsClusterReply, error)
}

type adminApiClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminApiClient(cc grpc.ClientConnInterface) AdminApiClient {
	return &adminApiClient{cc}
}

func (c *adminApiClient) ActiveTerminals(ctx context.Context, in *ActiveTerminalsRequest, opts ...grpc.CallOption) (*ActiveTerminalsReply, error) {
	out := new(ActiveTerminalsReply)
	err := c.cc.Invoke(ctx, "/mrpc_admin.AdminApi/ActiveTerminals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminApiClient) ActiveTerminalsCluster(ctx context.Context, in *ActiveTerminalsRequest, opts ...grpc.CallOption) (*ActiveTerminalsClusterReply, error) {
	out := new(ActiveTerminalsClusterReply)
	err := c.cc.Invoke(ctx, "/mrpc_admin.AdminApi/ActiveTerminalsCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminApiServer is the server API for AdminApi service.
// All implementations should embed UnimplementedAdminApiServer
// for forward compatibility
type AdminApiServer interface {
	// Active terminals running on THIS pod.
	ActiveTerminals(context.Context, *ActiveTerminalsRequest) (*ActiveTerminalsReply, error)
	// Active terminals across ALL pods of this StatefulSet/Deployment.
	// Lists peer pods via the Kubernetes API, then calls ActiveTerminals on each.
	ActiveTerminalsCluster(context.Context, *ActiveTerminalsRequest) (*ActiveTerminalsClusterReply, error)
}

// UnimplementedAdminApiServer should be embedded to have forward compatible implementations.
type UnimplementedAdminApiServer struct {
}

func (UnimplementedAdminApiServer) ActiveTerminals(context.Context, *ActiveTerminalsRequest) (*ActiveTerminalsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveTerminals not implemented")
}
func (UnimplementedAdminApiServer) ActiveTerminalsCluster(context.Context, *ActiveTerminalsRequest) (*ActiveTerminalsClusterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveTerminalsCluster not implemented")
}

// UnsafeAdminApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminApiServer will
// result in compilation errors.
type UnsafeAdminApiServer interface {
	mustEmbedUnimplementedAdminApiServer()
}

func RegisterAdminApiServer(s grpc.ServiceRegistrar, srv AdminApiServer) {
	s.RegisterService(&AdminApi_ServiceDesc, srv)
}

func _AdminApi_ActiveTerminals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveTerminalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminApiServer).ActiveTerminals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mrpc_admin.AdminApi/ActiveTerminals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminApiServer).ActiveTerminals(ctx, req.(*ActiveTerminalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminApi_ActiveTerminalsCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveTerminalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminApiServer).ActiveTerminalsCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mrpc_admin.AdminApi/ActiveTerminalsCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminApiServer).ActiveTerminalsCluster(ctx, req.(*ActiveTerminalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminApi_ServiceDesc is the grpc.ServiceDesc for AdminApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mrpc_admin.AdminApi",
	HandlerType: (*AdminApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActiveTerminals",
			Handler:    _AdminApi_ActiveTerminals_Handler,
		},
		{
			MethodName: "ActiveTerminalsCluster",
			Handler:    _AdminApi_ActiveTerminalsCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-admin.proto",
}
