// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-gui.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GuiClient is the client API for Gui service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuiClient interface {
	Login(ctx context.Context, in *GuiLoginRequest, opts ...grpc.CallOption) (*GuiLoginReply, error)
	BrokerSearch(ctx context.Context, in *GuiBrokerSearchRequest, opts ...grpc.CallOption) (*GuiBrokerSearchReply, error)
	LoginEx(ctx context.Context, in *GuiLoginExRequest, opts ...grpc.CallOption) (*GuiLoginExReply, error)
	CloseDialogs(ctx context.Context, in *GuiCloseDialogsRequest, opts ...grpc.CallOption) (*GuiCloseDialogsReply, error)
	DemoFindCompanies(ctx context.Context, in *GuiDemoFindCompaniesRequest, opts ...grpc.CallOption) (*GuiDemoFindCompaniesReply, error)
	DemoServersAndTypes(ctx context.Context, in *GuiDemoServersAndTypesRequest, opts ...grpc.CallOption) (*GuiDemoServersAndTypesReply, error)
	DemoOpenAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error)
	DemoEnumControls(ctx context.Context, in *GuiDemoEnumControlsRequest, opts ...grpc.CallOption) (*GuiDemoEnumControlsReply, error)
	DemoOpenAccountWithProgress(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (Gui_DemoOpenAccountWithProgressClient, error)
}

type guiClient struct {
	cc grpc.ClientConnInterface
}

func NewGuiClient(cc grpc.ClientConnInterface) GuiClient {
	return &guiClient{cc}
}

func (c *guiClient) Login(ctx context.Context, in *GuiLoginRequest, opts ...grpc.CallOption) (*GuiLoginReply, error) {
	out := new(GuiLoginReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) BrokerSearch(ctx context.Context, in *GuiBrokerSearchRequest, opts ...grpc.CallOption) (*GuiBrokerSearchReply, error) {
	out := new(GuiBrokerSearchReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/BrokerSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) LoginEx(ctx context.Context, in *GuiLoginExRequest, opts ...grpc.CallOption) (*GuiLoginExReply, error) {
	out := new(GuiLoginExReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/LoginEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) CloseDialogs(ctx context.Context, in *GuiCloseDialogsRequest, opts ...grpc.CallOption) (*GuiCloseDialogsReply, error) {
	out := new(GuiCloseDialogsReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/CloseDialogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) DemoFindCompanies(ctx context.Context, in *GuiDemoFindCompaniesRequest, opts ...grpc.CallOption) (*GuiDemoFindCompaniesReply, error) {
	out := new(GuiDemoFindCompaniesReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/DemoFindCompanies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) DemoServersAndTypes(ctx context.Context, in *GuiDemoServersAndTypesRequest, opts ...grpc.CallOption) (*GuiDemoServersAndTypesReply, error) {
	out := new(GuiDemoServersAndTypesReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/DemoServersAndTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) DemoOpenAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error) {
	out := new(GuiDemoOpenAccountReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/DemoOpenAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) DemoEnumControls(ctx context.Context, in *GuiDemoEnumControlsRequest, opts ...grpc.CallOption) (*GuiDemoEnumControlsReply, error) {
	out := new(GuiDemoEnumControlsReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Gui/DemoEnumControls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiClient) DemoOpenAccountWithProgress(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (Gui_DemoOpenAccountWithProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gui_ServiceDesc.Streams[0], "/mt5_term_api.Gui/DemoOpenAccountWithProgress", opts...)
	if err != nil {
		return nil, err
	}
	x := &guiDemoOpenAccountWithProgressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gui_DemoOpenAccountWithProgressClient interface {
	Recv() (*GuiDemoProgressEvent, error)
	grpc.ClientStream
}

type guiDemoOpenAccountWithProgressClient struct {
	grpc.ClientStream
}

func (x *guiDemoOpenAccountWithProgressClient) Recv() (*GuiDemoProgressEvent, error) {
	m := new(GuiDemoProgressEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GuiServer is the server API for Gui service.
// All implementations should embed UnimplementedGuiServer
// for forward compatibility
type GuiServer interface {
	Login(context.Context, *GuiLoginRequest) (*GuiLoginReply, error)
	BrokerSearch(context.Context, *GuiBrokerSearchRequest) (*GuiBrokerSearchReply, error)
	LoginEx(context.Context, *GuiLoginExRequest) (*GuiLoginExReply, error)
	CloseDialogs(context.Context, *GuiCloseDialogsRequest) (*GuiCloseDialogsReply, error)
	DemoFindCompanies(context.Context, *GuiDemoFindCompaniesRequest) (*GuiDemoFindCompaniesReply, error)
	DemoServersAndTypes(context.Context, *GuiDemoServersAndTypesRequest) (*GuiDemoServersAndTypesReply, error)
	DemoOpenAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error)
	DemoEnumControls(context.Context, *GuiDemoEnumControlsRequest) (*GuiDemoEnumControlsReply, error)
	DemoOpenAccountWithProgress(*GuiDemoOpenAccountRequest, Gui_DemoOpenAccountWithProgressServer) error
}

// UnimplementedGuiServer should be embedded to have forward compatible implementations.
type UnimplementedGuiServer struct {
}

func (UnimplementedGuiServer) Login(context.Context, *GuiLoginRequest) (*GuiLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGuiServer) BrokerSearch(context.Context, *GuiBrokerSearchRequest) (*GuiBrokerSearchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrokerSearch not implemented")
}
func (UnimplementedGuiServer) LoginEx(context.Context, *GuiLoginExRequest) (*GuiLoginExReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginEx not implemented")
}
func (UnimplementedGuiServer) CloseDialogs(context.Context, *GuiCloseDialogsRequest) (*GuiCloseDialogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseDialogs not implemented")
}
func (UnimplementedGuiServer) DemoFindCompanies(context.Context, *GuiDemoFindCompaniesRequest) (*GuiDemoFindCompaniesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoFindCompanies not implemented")
}
func (UnimplementedGuiServer) DemoServersAndTypes(context.Context, *GuiDemoServersAndTypesRequest) (*GuiDemoServersAndTypesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoServersAndTypes not implemented")
}
func (UnimplementedGuiServer) DemoOpenAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoOpenAccount not implemented")
}
func (UnimplementedGuiServer) DemoEnumControls(context.Context, *GuiDemoEnumControlsRequest) (*GuiDemoEnumControlsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoEnumControls not implemented")
}
func (UnimplementedGuiServer) DemoOpenAccountWithProgress(*GuiDemoOpenAccountRequest, Gui_DemoOpenAccountWithProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method DemoOpenAccountWithProgress not implemented")
}

// UnsafeGuiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuiServer will
// result in compilation errors.
type UnsafeGuiServer interface {
	mustEmbedUnimplementedGuiServer()
}

func RegisterGuiServer(s grpc.ServiceRegistrar, srv GuiServer) {
	s.RegisterService(&Gui_ServiceDesc, srv)
}

func _Gui_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).Login(ctx, req.(*GuiLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_BrokerSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiBrokerSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).BrokerSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/BrokerSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).BrokerSearch(ctx, req.(*GuiBrokerSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_LoginEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiLoginExRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).LoginEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/LoginEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).LoginEx(ctx, req.(*GuiLoginExRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_CloseDialogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiCloseDialogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).CloseDialogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/CloseDialogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).CloseDialogs(ctx, req.(*GuiCloseDialogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_DemoFindCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoFindCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).DemoFindCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/DemoFindCompanies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).DemoFindCompanies(ctx, req.(*GuiDemoFindCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_DemoServersAndTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoServersAndTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).DemoServersAndTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/DemoServersAndTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).DemoServersAndTypes(ctx, req.(*GuiDemoServersAndTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_DemoOpenAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoOpenAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).DemoOpenAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/DemoOpenAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).DemoOpenAccount(ctx, req.(*GuiDemoOpenAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_DemoEnumControls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoEnumControlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiServer).DemoEnumControls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Gui/DemoEnumControls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiServer).DemoEnumControls(ctx, req.(*GuiDemoEnumControlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gui_DemoOpenAccountWithProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GuiDemoOpenAccountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuiServer).DemoOpenAccountWithProgress(m, &guiDemoOpenAccountWithProgressServer{stream})
}

type Gui_DemoOpenAccountWithProgressServer interface {
	Send(*GuiDemoProgressEvent) error
	grpc.ServerStream
}

type guiDemoOpenAccountWithProgressServer struct {
	grpc.ServerStream
}

func (x *guiDemoOpenAccountWithProgressServer) Send(m *GuiDemoProgressEvent) error {
	return x.ServerStream.SendMsg(m)
}

// Gui_ServiceDesc is the grpc.ServiceDesc for Gui service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gui_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.Gui",
	HandlerType: (*GuiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Gui_Login_Handler,
		},
		{
			MethodName: "BrokerSearch",
			Handler:    _Gui_BrokerSearch_Handler,
		},
		{
			MethodName: "LoginEx",
			Handler:    _Gui_LoginEx_Handler,
		},
		{
			MethodName: "CloseDialogs",
			Handler:    _Gui_CloseDialogs_Handler,
		},
		{
			MethodName: "DemoFindCompanies",
			Handler:    _Gui_DemoFindCompanies_Handler,
		},
		{
			MethodName: "DemoServersAndTypes",
			Handler:    _Gui_DemoServersAndTypes_Handler,
		},
		{
			MethodName: "DemoOpenAccount",
			Handler:    _Gui_DemoOpenAccount_Handler,
		},
		{
			MethodName: "DemoEnumControls",
			Handler:    _Gui_DemoEnumControls_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DemoOpenAccountWithProgress",
			Handler:       _Gui_DemoOpenAccountWithProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mt5-term-api-gui.proto",
}
