// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-internal-charts.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InternalChartsClient is the client API for InternalCharts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalChartsClient interface {
	OpenChartForSymbol(ctx context.Context, in *OpenChartForSymbolRequest, opts ...grpc.CallOption) (*OpenChartForSymbolReply, error)
	CloseChartForSymbol(ctx context.Context, in *CloseChartForSymbolRequest, opts ...grpc.CallOption) (*CloseChartForSymbolReply, error)
	OpenChartWithEa(ctx context.Context, in *OpenChartWithEaRequest, opts ...grpc.CallOption) (*OpenChartWithEaReply, error)
	SaveChartTemplate(ctx context.Context, in *SaveChartTemplateRequest, opts ...grpc.CallOption) (*SaveChartTemplateReply, error)
}

type internalChartsClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalChartsClient(cc grpc.ClientConnInterface) InternalChartsClient {
	return &internalChartsClient{cc}
}

func (c *internalChartsClient) OpenChartForSymbol(ctx context.Context, in *OpenChartForSymbolRequest, opts ...grpc.CallOption) (*OpenChartForSymbolReply, error) {
	out := new(OpenChartForSymbolReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.InternalCharts/OpenChartForSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalChartsClient) CloseChartForSymbol(ctx context.Context, in *CloseChartForSymbolRequest, opts ...grpc.CallOption) (*CloseChartForSymbolReply, error) {
	out := new(CloseChartForSymbolReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.InternalCharts/CloseChartForSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalChartsClient) OpenChartWithEa(ctx context.Context, in *OpenChartWithEaRequest, opts ...grpc.CallOption) (*OpenChartWithEaReply, error) {
	out := new(OpenChartWithEaReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.InternalCharts/OpenChartWithEa", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalChartsClient) SaveChartTemplate(ctx context.Context, in *SaveChartTemplateRequest, opts ...grpc.CallOption) (*SaveChartTemplateReply, error) {
	out := new(SaveChartTemplateReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.InternalCharts/SaveChartTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalChartsServer is the server API for InternalCharts service.
// All implementations should embed UnimplementedInternalChartsServer
// for forward compatibility
type InternalChartsServer interface {
	OpenChartForSymbol(context.Context, *OpenChartForSymbolRequest) (*OpenChartForSymbolReply, error)
	CloseChartForSymbol(context.Context, *CloseChartForSymbolRequest) (*CloseChartForSymbolReply, error)
	OpenChartWithEa(context.Context, *OpenChartWithEaRequest) (*OpenChartWithEaReply, error)
	SaveChartTemplate(context.Context, *SaveChartTemplateRequest) (*SaveChartTemplateReply, error)
}

// UnimplementedInternalChartsServer should be embedded to have forward compatible implementations.
type UnimplementedInternalChartsServer struct {
}

func (UnimplementedInternalChartsServer) OpenChartForSymbol(context.Context, *OpenChartForSymbolRequest) (*OpenChartForSymbolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChartForSymbol not implemented")
}
func (UnimplementedInternalChartsServer) CloseChartForSymbol(context.Context, *CloseChartForSymbolRequest) (*CloseChartForSymbolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseChartForSymbol not implemented")
}
func (UnimplementedInternalChartsServer) OpenChartWithEa(context.Context, *OpenChartWithEaRequest) (*OpenChartWithEaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChartWithEa not implemented")
}
func (UnimplementedInternalChartsServer) SaveChartTemplate(context.Context, *SaveChartTemplateRequest) (*SaveChartTemplateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveChartTemplate not implemented")
}

// UnsafeInternalChartsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalChartsServer will
// result in compilation errors.
type UnsafeInternalChartsServer interface {
	mustEmbedUnimplementedInternalChartsServer()
}

func RegisterInternalChartsServer(s grpc.ServiceRegistrar, srv InternalChartsServer) {
	s.RegisterService(&InternalCharts_ServiceDesc, srv)
}

func _InternalCharts_OpenChartForSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChartForSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalChartsServer).OpenChartForSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.InternalCharts/OpenChartForSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalChartsServer).OpenChartForSymbol(ctx, req.(*OpenChartForSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCharts_CloseChartForSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseChartForSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalChartsServer).CloseChartForSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.InternalCharts/CloseChartForSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalChartsServer).CloseChartForSymbol(ctx, req.(*CloseChartForSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCharts_OpenChartWithEa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChartWithEaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalChartsServer).OpenChartWithEa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.InternalCharts/OpenChartWithEa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalChartsServer).OpenChartWithEa(ctx, req.(*OpenChartWithEaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalCharts_SaveChartTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveChartTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalChartsServer).SaveChartTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.InternalCharts/SaveChartTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalChartsServer).SaveChartTemplate(ctx, req.(*SaveChartTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalCharts_ServiceDesc is the grpc.ServiceDesc for InternalCharts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalCharts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.InternalCharts",
	HandlerType: (*InternalChartsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenChartForSymbol",
			Handler:    _InternalCharts_OpenChartForSymbol_Handler,
		},
		{
			MethodName: "CloseChartForSymbol",
			Handler:    _InternalCharts_CloseChartForSymbol_Handler,
		},
		{
			MethodName: "OpenChartWithEa",
			Handler:    _InternalCharts_OpenChartWithEa_Handler,
		},
		{
			MethodName: "SaveChartTemplate",
			Handler:    _InternalCharts_SaveChartTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-internal-charts.proto",
}
