// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-trade-stats.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradeStatsClient is the client API for TradeStats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeStatsClient interface {
	// Trading statistics calculated from order history and open orders
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-01-01T00:00:00"
	//	}
	TradeStats(ctx context.Context, in *TradeStatsRequest, opts ...grpc.CallOption) (*TradeStatsReply, error)
	// Trading statistics with equity history chart points
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-01-01T00:00:00",
	//	  "excludeSameBars": true
	//	}
	TradeStatsEquityHistory(ctx context.Context, in *TradeStatsEquityHistoryRequest, opts ...grpc.CallOption) (*TradeStatsEquityHistoryReply, error)
	// Equity history curve points with drawdown calculation
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-10-01T00:00:00",
	//	  "excludeSameBars": true
	//	}
	EquityHistory(ctx context.Context, in *EquityHistoryRequest, opts ...grpc.CallOption) (*EquityHistoryReply, error)
	// Maximum and minimum unrealized profit/loss per trade
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-01-01T00:00:00"
	//	}
	TradeUnrealizedPL(ctx context.Context, in *TradeUnrealizedPLRequest, opts ...grpc.CallOption) (*TradeUnrealizedPLReply, error)
}

type tradeStatsClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeStatsClient(cc grpc.ClientConnInterface) TradeStatsClient {
	return &tradeStatsClient{cc}
}

func (c *tradeStatsClient) TradeStats(ctx context.Context, in *TradeStatsRequest, opts ...grpc.CallOption) (*TradeStatsReply, error) {
	out := new(TradeStatsReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradeStats/TradeStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeStatsClient) TradeStatsEquityHistory(ctx context.Context, in *TradeStatsEquityHistoryRequest, opts ...grpc.CallOption) (*TradeStatsEquityHistoryReply, error) {
	out := new(TradeStatsEquityHistoryReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradeStats/TradeStatsEquityHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeStatsClient) EquityHistory(ctx context.Context, in *EquityHistoryRequest, opts ...grpc.CallOption) (*EquityHistoryReply, error) {
	out := new(EquityHistoryReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradeStats/EquityHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeStatsClient) TradeUnrealizedPL(ctx context.Context, in *TradeUnrealizedPLRequest, opts ...grpc.CallOption) (*TradeUnrealizedPLReply, error) {
	out := new(TradeUnrealizedPLReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.TradeStats/TradeUnrealizedPL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeStatsServer is the server API for TradeStats service.
// All implementations should embed UnimplementedTradeStatsServer
// for forward compatibility
type TradeStatsServer interface {
	// Trading statistics calculated from order history and open orders
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-01-01T00:00:00"
	//	}
	TradeStats(context.Context, *TradeStatsRequest) (*TradeStatsReply, error)
	// Trading statistics with equity history chart points
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-01-01T00:00:00",
	//	  "excludeSameBars": true
	//	}
	TradeStatsEquityHistory(context.Context, *TradeStatsEquityHistoryRequest) (*TradeStatsEquityHistoryReply, error)
	// Equity history curve points with drawdown calculation
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-10-01T00:00:00",
	//	  "excludeSameBars": true
	//	}
	EquityHistory(context.Context, *EquityHistoryRequest) (*EquityHistoryReply, error)
	// Maximum and minimum unrealized profit/loss per trade
	// [DefaultValues]
	//
	//	{
	//	  "from": "2024-01-01T00:00:00"
	//	}
	TradeUnrealizedPL(context.Context, *TradeUnrealizedPLRequest) (*TradeUnrealizedPLReply, error)
}

// UnimplementedTradeStatsServer should be embedded to have forward compatible implementations.
type UnimplementedTradeStatsServer struct {
}

func (UnimplementedTradeStatsServer) TradeStats(context.Context, *TradeStatsRequest) (*TradeStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeStats not implemented")
}
func (UnimplementedTradeStatsServer) TradeStatsEquityHistory(context.Context, *TradeStatsEquityHistoryRequest) (*TradeStatsEquityHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeStatsEquityHistory not implemented")
}
func (UnimplementedTradeStatsServer) EquityHistory(context.Context, *EquityHistoryRequest) (*EquityHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EquityHistory not implemented")
}
func (UnimplementedTradeStatsServer) TradeUnrealizedPL(context.Context, *TradeUnrealizedPLRequest) (*TradeUnrealizedPLReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeUnrealizedPL not implemented")
}

// UnsafeTradeStatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeStatsServer will
// result in compilation errors.
type UnsafeTradeStatsServer interface {
	mustEmbedUnimplementedTradeStatsServer()
}

func RegisterTradeStatsServer(s grpc.ServiceRegistrar, srv TradeStatsServer) {
	s.RegisterService(&TradeStats_ServiceDesc, srv)
}

func _TradeStats_TradeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeStatsServer).TradeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradeStats/TradeStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeStatsServer).TradeStats(ctx, req.(*TradeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeStats_TradeStatsEquityHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeStatsEquityHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeStatsServer).TradeStatsEquityHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradeStats/TradeStatsEquityHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeStatsServer).TradeStatsEquityHistory(ctx, req.(*TradeStatsEquityHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeStats_EquityHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquityHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeStatsServer).EquityHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradeStats/EquityHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeStatsServer).EquityHistory(ctx, req.(*EquityHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeStats_TradeUnrealizedPL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeUnrealizedPLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeStatsServer).TradeUnrealizedPL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.TradeStats/TradeUnrealizedPL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeStatsServer).TradeUnrealizedPL(ctx, req.(*TradeUnrealizedPLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeStats_ServiceDesc is the grpc.ServiceDesc for TradeStats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeStats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.TradeStats",
	HandlerType: (*TradeStatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TradeStats",
			Handler:    _TradeStats_TradeStats_Handler,
		},
		{
			MethodName: "TradeStatsEquityHistory",
			Handler:    _TradeStats_TradeStatsEquityHistory_Handler,
		},
		{
			MethodName: "EquityHistory",
			Handler:    _TradeStats_EquityHistory_Handler,
		},
		{
			MethodName: "TradeUnrealizedPL",
			Handler:    _TradeStats_TradeUnrealizedPL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-trade-stats.proto",
}
