// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-charts.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChartsClient is the client API for Charts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChartsClient interface {
	OpenTerminalChartWithEa(ctx context.Context, in *OpenTerminalChartWithEaRequest, opts ...grpc.CallOption) (*OpenTerminalChartWithEaReply, error)
	GetEaParams(ctx context.Context, in *GetEaParamsRequest, opts ...grpc.CallOption) (*GetEaParamsReply, error)
}

type chartsClient struct {
	cc grpc.ClientConnInterface
}

func NewChartsClient(cc grpc.ClientConnInterface) ChartsClient {
	return &chartsClient{cc}
}

func (c *chartsClient) OpenTerminalChartWithEa(ctx context.Context, in *OpenTerminalChartWithEaRequest, opts ...grpc.CallOption) (*OpenTerminalChartWithEaReply, error) {
	out := new(OpenTerminalChartWithEaReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Charts/OpenTerminalChartWithEa", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chartsClient) GetEaParams(ctx context.Context, in *GetEaParamsRequest, opts ...grpc.CallOption) (*GetEaParamsReply, error) {
	out := new(GetEaParamsReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Charts/GetEaParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChartsServer is the server API for Charts service.
// All implementations should embed UnimplementedChartsServer
// for forward compatibility
type ChartsServer interface {
	OpenTerminalChartWithEa(context.Context, *OpenTerminalChartWithEaRequest) (*OpenTerminalChartWithEaReply, error)
	GetEaParams(context.Context, *GetEaParamsRequest) (*GetEaParamsReply, error)
}

// UnimplementedChartsServer should be embedded to have forward compatible implementations.
type UnimplementedChartsServer struct {
}

func (UnimplementedChartsServer) OpenTerminalChartWithEa(context.Context, *OpenTerminalChartWithEaRequest) (*OpenTerminalChartWithEaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTerminalChartWithEa not implemented")
}
func (UnimplementedChartsServer) GetEaParams(context.Context, *GetEaParamsRequest) (*GetEaParamsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEaParams not implemented")
}

// UnsafeChartsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChartsServer will
// result in compilation errors.
type UnsafeChartsServer interface {
	mustEmbedUnimplementedChartsServer()
}

func RegisterChartsServer(s grpc.ServiceRegistrar, srv ChartsServer) {
	s.RegisterService(&Charts_ServiceDesc, srv)
}

func _Charts_OpenTerminalChartWithEa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTerminalChartWithEaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServer).OpenTerminalChartWithEa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Charts/OpenTerminalChartWithEa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServer).OpenTerminalChartWithEa(ctx, req.(*OpenTerminalChartWithEaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Charts_GetEaParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEaParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChartsServer).GetEaParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Charts/GetEaParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChartsServer).GetEaParams(ctx, req.(*GetEaParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Charts_ServiceDesc is the grpc.ServiceDesc for Charts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Charts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.Charts",
	HandlerType: (*ChartsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTerminalChartWithEa",
			Handler:    _Charts_OpenTerminalChartWithEa_Handler,
		},
		{
			MethodName: "GetEaParams",
			Handler:    _Charts_GetEaParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-charts.proto",
}
