// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mt5-term-api-account-information.proto

package _go

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountInfoDoublePropertyType int32

const (
	AccountInfoDoublePropertyType_ACCOUNT_BALANCE            AccountInfoDoublePropertyType = 0  // Account balance in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_CREDIT             AccountInfoDoublePropertyType = 1  // Account credit in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_PROFIT             AccountInfoDoublePropertyType = 2  // Current profit of an account in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_EQUITY             AccountInfoDoublePropertyType = 3  // Account equity in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN             AccountInfoDoublePropertyType = 4  // Account margin used in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN_FREE        AccountInfoDoublePropertyType = 5  // Free margin of an account in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN_LEVEL       AccountInfoDoublePropertyType = 6  // Account margin level in percents
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN_SO_CALL     AccountInfoDoublePropertyType = 7  // Margin call level. Depending on the set ACCOUNT_MARGIN_SO_MODE is expressed in percents or in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN_SO_SO       AccountInfoDoublePropertyType = 8  // Margin stop out level. Depending on the set ACCOUNT_MARGIN_SO_MODE is expressed in percents or in the deposit currency
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN_INITIAL     AccountInfoDoublePropertyType = 9  // Initial margin. The amount reserved on an account to cover the margin of all pending orders
	AccountInfoDoublePropertyType_ACCOUNT_MARGIN_MAINTENANCE AccountInfoDoublePropertyType = 10 // Maintenance margin. The minimum equity reserved on an account to cover the minimum amount of all open positions
	AccountInfoDoublePropertyType_ACCOUNT_ASSETS             AccountInfoDoublePropertyType = 11 // The current assets of an account
	AccountInfoDoublePropertyType_ACCOUNT_LIABILITIES        AccountInfoDoublePropertyType = 12 // The current liabilities on an account
	AccountInfoDoublePropertyType_ACCOUNT_COMMISSION_BLOCKED AccountInfoDoublePropertyType = 13 // The current blocked commission amount on an account
)

// Enum value maps for AccountInfoDoublePropertyType.
var (
	AccountInfoDoublePropertyType_name = map[int32]string{
		0:  "ACCOUNT_BALANCE",
		1:  "ACCOUNT_CREDIT",
		2:  "ACCOUNT_PROFIT",
		3:  "ACCOUNT_EQUITY",
		4:  "ACCOUNT_MARGIN",
		5:  "ACCOUNT_MARGIN_FREE",
		6:  "ACCOUNT_MARGIN_LEVEL",
		7:  "ACCOUNT_MARGIN_SO_CALL",
		8:  "ACCOUNT_MARGIN_SO_SO",
		9:  "ACCOUNT_MARGIN_INITIAL",
		10: "ACCOUNT_MARGIN_MAINTENANCE",
		11: "ACCOUNT_ASSETS",
		12: "ACCOUNT_LIABILITIES",
		13: "ACCOUNT_COMMISSION_BLOCKED",
	}
	AccountInfoDoublePropertyType_value = map[string]int32{
		"ACCOUNT_BALANCE":            0,
		"ACCOUNT_CREDIT":             1,
		"ACCOUNT_PROFIT":             2,
		"ACCOUNT_EQUITY":             3,
		"ACCOUNT_MARGIN":             4,
		"ACCOUNT_MARGIN_FREE":        5,
		"ACCOUNT_MARGIN_LEVEL":       6,
		"ACCOUNT_MARGIN_SO_CALL":     7,
		"ACCOUNT_MARGIN_SO_SO":       8,
		"ACCOUNT_MARGIN_INITIAL":     9,
		"ACCOUNT_MARGIN_MAINTENANCE": 10,
		"ACCOUNT_ASSETS":             11,
		"ACCOUNT_LIABILITIES":        12,
		"ACCOUNT_COMMISSION_BLOCKED": 13,
	}
)

func (x AccountInfoDoublePropertyType) Enum() *AccountInfoDoublePropertyType {
	p := new(AccountInfoDoublePropertyType)
	*p = x
	return p
}

func (x AccountInfoDoublePropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountInfoDoublePropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_account_information_proto_enumTypes[0].Descriptor()
}

func (AccountInfoDoublePropertyType) Type() protoreflect.EnumType {
	return &file_mt5_term_api_account_information_proto_enumTypes[0]
}

func (x AccountInfoDoublePropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountInfoDoublePropertyType.Descriptor instead.
func (AccountInfoDoublePropertyType) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{0}
}

type AccountInfoIntegerPropertyType int32

const (
	AccountInfoIntegerPropertyType_ACCOUNT_LOGIN           AccountInfoIntegerPropertyType = 0  // Account number - returned type long
	AccountInfoIntegerPropertyType_ACCOUNT_TRADE_MODE      AccountInfoIntegerPropertyType = 1  // Account trade mode - returned type ENUM_ACCOUNT_TRADE_MODE
	AccountInfoIntegerPropertyType_ACCOUNT_LEVERAGE        AccountInfoIntegerPropertyType = 2  // Account leverage - long
	AccountInfoIntegerPropertyType_ACCOUNT_LIMIT_ORDERS    AccountInfoIntegerPropertyType = 3  // Maximum allowed number of open positions and active pending orders (in total), 0  unlimited - returned type int
	AccountInfoIntegerPropertyType_ACCOUNT_MARGIN_SO_MODE  AccountInfoIntegerPropertyType = 4  // Mode for setting the minimal allowed margin - returned type ENUM_ACCOUNT_STOP_OUT_MODE
	AccountInfoIntegerPropertyType_ACCOUNT_TRADE_ALLOWED   AccountInfoIntegerPropertyType = 5  // Allowed trade for the current account - returned type bool (1 or 0)
	AccountInfoIntegerPropertyType_ACCOUNT_TRADE_EXPERT    AccountInfoIntegerPropertyType = 6  // Allowed trade for an Expert Advisor - return type bool (1 or 0)
	AccountInfoIntegerPropertyType_ACCOUNT_MARGIN_MODE     AccountInfoIntegerPropertyType = 7  // Margin calculation mode - return type ENUM_ACCOUNT_MARGIN_MODE
	AccountInfoIntegerPropertyType_ACCOUNT_CURRENCY_DIGITS AccountInfoIntegerPropertyType = 8  // The number of decimal places in the account currency, which are required for an accurate display of trading results - returned type int
	AccountInfoIntegerPropertyType_ACCOUNT_FIFO_CLOSE      AccountInfoIntegerPropertyType = 9  // An indication showing that positions can only be closed by FIFO rule. If the property value is set to true, then each symbol positions will be closed in the same order, in which they are opened, starting with the oldest one. In case of an attempt to close positions in a different order, the trader will receive an appropriate error.  - return type bool (1 or 0)
	AccountInfoIntegerPropertyType_ACCOUNT_HEDGE_ALLOWED   AccountInfoIntegerPropertyType = 10 // Allowed opposite positions on a single symbol - return type bool (1 or 0)
)

// Enum value maps for AccountInfoIntegerPropertyType.
var (
	AccountInfoIntegerPropertyType_name = map[int32]string{
		0:  "ACCOUNT_LOGIN",
		1:  "ACCOUNT_TRADE_MODE",
		2:  "ACCOUNT_LEVERAGE",
		3:  "ACCOUNT_LIMIT_ORDERS",
		4:  "ACCOUNT_MARGIN_SO_MODE",
		5:  "ACCOUNT_TRADE_ALLOWED",
		6:  "ACCOUNT_TRADE_EXPERT",
		7:  "ACCOUNT_MARGIN_MODE",
		8:  "ACCOUNT_CURRENCY_DIGITS",
		9:  "ACCOUNT_FIFO_CLOSE",
		10: "ACCOUNT_HEDGE_ALLOWED",
	}
	AccountInfoIntegerPropertyType_value = map[string]int32{
		"ACCOUNT_LOGIN":           0,
		"ACCOUNT_TRADE_MODE":      1,
		"ACCOUNT_LEVERAGE":        2,
		"ACCOUNT_LIMIT_ORDERS":    3,
		"ACCOUNT_MARGIN_SO_MODE":  4,
		"ACCOUNT_TRADE_ALLOWED":   5,
		"ACCOUNT_TRADE_EXPERT":    6,
		"ACCOUNT_MARGIN_MODE":     7,
		"ACCOUNT_CURRENCY_DIGITS": 8,
		"ACCOUNT_FIFO_CLOSE":      9,
		"ACCOUNT_HEDGE_ALLOWED":   10,
	}
)

func (x AccountInfoIntegerPropertyType) Enum() *AccountInfoIntegerPropertyType {
	p := new(AccountInfoIntegerPropertyType)
	*p = x
	return p
}

func (x AccountInfoIntegerPropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountInfoIntegerPropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_account_information_proto_enumTypes[1].Descriptor()
}

func (AccountInfoIntegerPropertyType) Type() protoreflect.EnumType {
	return &file_mt5_term_api_account_information_proto_enumTypes[1]
}

func (x AccountInfoIntegerPropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountInfoIntegerPropertyType.Descriptor instead.
func (AccountInfoIntegerPropertyType) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{1}
}

type AccountInfoStringPropertyType int32

const (
	AccountInfoStringPropertyType_ACCOUNT_NAME     AccountInfoStringPropertyType = 0 // Client name
	AccountInfoStringPropertyType_ACCOUNT_SERVER   AccountInfoStringPropertyType = 1 // Trade server name
	AccountInfoStringPropertyType_ACCOUNT_CURRENCY AccountInfoStringPropertyType = 2 // Account currency
	AccountInfoStringPropertyType_ACCOUNT_COMPANY  AccountInfoStringPropertyType = 3 // Name of a company that serves the account
)

// Enum value maps for AccountInfoStringPropertyType.
var (
	AccountInfoStringPropertyType_name = map[int32]string{
		0: "ACCOUNT_NAME",
		1: "ACCOUNT_SERVER",
		2: "ACCOUNT_CURRENCY",
		3: "ACCOUNT_COMPANY",
	}
	AccountInfoStringPropertyType_value = map[string]int32{
		"ACCOUNT_NAME":     0,
		"ACCOUNT_SERVER":   1,
		"ACCOUNT_CURRENCY": 2,
		"ACCOUNT_COMPANY":  3,
	}
)

func (x AccountInfoStringPropertyType) Enum() *AccountInfoStringPropertyType {
	p := new(AccountInfoStringPropertyType)
	*p = x
	return p
}

func (x AccountInfoStringPropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountInfoStringPropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_account_information_proto_enumTypes[2].Descriptor()
}

func (AccountInfoStringPropertyType) Type() protoreflect.EnumType {
	return &file_mt5_term_api_account_information_proto_enumTypes[2]
}

func (x AccountInfoStringPropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountInfoStringPropertyType.Descriptor instead.
func (AccountInfoStringPropertyType) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{2}
}

type AccountInfoDoubleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyId AccountInfoDoublePropertyType `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3,enum=mt5_term_api.AccountInfoDoublePropertyType" json:"property_id,omitempty"`
}

func (x *AccountInfoDoubleRequest) Reset() {
	*x = AccountInfoDoubleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoDoubleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoDoubleRequest) ProtoMessage() {}

func (x *AccountInfoDoubleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoDoubleRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoDoubleRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInfoDoubleRequest) GetPropertyId() AccountInfoDoublePropertyType {
	if x != nil {
		return x.PropertyId
	}
	return AccountInfoDoublePropertyType_ACCOUNT_BALANCE
}

type AccountInfoDoubleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*AccountInfoDoubleReply_Data
	//	*AccountInfoDoubleReply_Error
	Response isAccountInfoDoubleReply_Response `protobuf_oneof:"response"`
}

func (x *AccountInfoDoubleReply) Reset() {
	*x = AccountInfoDoubleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoDoubleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoDoubleReply) ProtoMessage() {}

func (x *AccountInfoDoubleReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoDoubleReply.ProtoReflect.Descriptor instead.
func (*AccountInfoDoubleReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{1}
}

func (m *AccountInfoDoubleReply) GetResponse() isAccountInfoDoubleReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *AccountInfoDoubleReply) GetData() *AccountInfoDoubleData {
	if x, ok := x.GetResponse().(*AccountInfoDoubleReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *AccountInfoDoubleReply) GetError() *Error {
	if x, ok := x.GetResponse().(*AccountInfoDoubleReply_Error); ok {
		return x.Error
	}
	return nil
}

type isAccountInfoDoubleReply_Response interface {
	isAccountInfoDoubleReply_Response()
}

type AccountInfoDoubleReply_Data struct {
	Data *AccountInfoDoubleData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type AccountInfoDoubleReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AccountInfoDoubleReply_Data) isAccountInfoDoubleReply_Response() {}

func (*AccountInfoDoubleReply_Error) isAccountInfoDoubleReply_Response() {}

type AccountInfoDoubleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedValue float64 `protobuf:"fixed64,1,opt,name=requested_value,json=requestedValue,proto3" json:"requested_value,omitempty"`
}

func (x *AccountInfoDoubleData) Reset() {
	*x = AccountInfoDoubleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoDoubleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoDoubleData) ProtoMessage() {}

func (x *AccountInfoDoubleData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoDoubleData.ProtoReflect.Descriptor instead.
func (*AccountInfoDoubleData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{2}
}

func (x *AccountInfoDoubleData) GetRequestedValue() float64 {
	if x != nil {
		return x.RequestedValue
	}
	return 0
}

type AccountInfoIntegerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyId AccountInfoIntegerPropertyType `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3,enum=mt5_term_api.AccountInfoIntegerPropertyType" json:"property_id,omitempty"`
}

func (x *AccountInfoIntegerRequest) Reset() {
	*x = AccountInfoIntegerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoIntegerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoIntegerRequest) ProtoMessage() {}

func (x *AccountInfoIntegerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoIntegerRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoIntegerRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{3}
}

func (x *AccountInfoIntegerRequest) GetPropertyId() AccountInfoIntegerPropertyType {
	if x != nil {
		return x.PropertyId
	}
	return AccountInfoIntegerPropertyType_ACCOUNT_LOGIN
}

type AccountInfoIntegerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*AccountInfoIntegerReply_Data
	//	*AccountInfoIntegerReply_Error
	Response isAccountInfoIntegerReply_Response `protobuf_oneof:"response"`
}

func (x *AccountInfoIntegerReply) Reset() {
	*x = AccountInfoIntegerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoIntegerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoIntegerReply) ProtoMessage() {}

func (x *AccountInfoIntegerReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoIntegerReply.ProtoReflect.Descriptor instead.
func (*AccountInfoIntegerReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{4}
}

func (m *AccountInfoIntegerReply) GetResponse() isAccountInfoIntegerReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *AccountInfoIntegerReply) GetData() *AccountInfoIntegerData {
	if x, ok := x.GetResponse().(*AccountInfoIntegerReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *AccountInfoIntegerReply) GetError() *Error {
	if x, ok := x.GetResponse().(*AccountInfoIntegerReply_Error); ok {
		return x.Error
	}
	return nil
}

type isAccountInfoIntegerReply_Response interface {
	isAccountInfoIntegerReply_Response()
}

type AccountInfoIntegerReply_Data struct {
	Data *AccountInfoIntegerData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type AccountInfoIntegerReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AccountInfoIntegerReply_Data) isAccountInfoIntegerReply_Response() {}

func (*AccountInfoIntegerReply_Error) isAccountInfoIntegerReply_Response() {}

type AccountInfoIntegerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedValue int64 `protobuf:"varint,1,opt,name=requested_value,json=requestedValue,proto3" json:"requested_value,omitempty"`
}

func (x *AccountInfoIntegerData) Reset() {
	*x = AccountInfoIntegerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoIntegerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoIntegerData) ProtoMessage() {}

func (x *AccountInfoIntegerData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoIntegerData.ProtoReflect.Descriptor instead.
func (*AccountInfoIntegerData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{5}
}

func (x *AccountInfoIntegerData) GetRequestedValue() int64 {
	if x != nil {
		return x.RequestedValue
	}
	return 0
}

type AccountInfoStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyId AccountInfoStringPropertyType `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3,enum=mt5_term_api.AccountInfoStringPropertyType" json:"property_id,omitempty"`
}

func (x *AccountInfoStringRequest) Reset() {
	*x = AccountInfoStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoStringRequest) ProtoMessage() {}

func (x *AccountInfoStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoStringRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoStringRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{6}
}

func (x *AccountInfoStringRequest) GetPropertyId() AccountInfoStringPropertyType {
	if x != nil {
		return x.PropertyId
	}
	return AccountInfoStringPropertyType_ACCOUNT_NAME
}

type AccountInfoStringReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*AccountInfoStringReply_Data
	//	*AccountInfoStringReply_Error
	Response isAccountInfoStringReply_Response `protobuf_oneof:"response"`
}

func (x *AccountInfoStringReply) Reset() {
	*x = AccountInfoStringReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoStringReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoStringReply) ProtoMessage() {}

func (x *AccountInfoStringReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoStringReply.ProtoReflect.Descriptor instead.
func (*AccountInfoStringReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{7}
}

func (m *AccountInfoStringReply) GetResponse() isAccountInfoStringReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *AccountInfoStringReply) GetData() *AccountInfoStringData {
	if x, ok := x.GetResponse().(*AccountInfoStringReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *AccountInfoStringReply) GetError() *Error {
	if x, ok := x.GetResponse().(*AccountInfoStringReply_Error); ok {
		return x.Error
	}
	return nil
}

type isAccountInfoStringReply_Response interface {
	isAccountInfoStringReply_Response()
}

type AccountInfoStringReply_Data struct {
	Data *AccountInfoStringData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type AccountInfoStringReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AccountInfoStringReply_Data) isAccountInfoStringReply_Response() {}

func (*AccountInfoStringReply_Error) isAccountInfoStringReply_Response() {}

type AccountInfoStringData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestedValue string `protobuf:"bytes,1,opt,name=requested_value,json=requestedValue,proto3" json:"requested_value,omitempty"`
}

func (x *AccountInfoStringData) Reset() {
	*x = AccountInfoStringData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_account_information_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoStringData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoStringData) ProtoMessage() {}

func (x *AccountInfoStringData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_account_information_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoStringData.ProtoReflect.Descriptor instead.
func (*AccountInfoStringData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_account_information_proto_rawDescGZIP(), []int{8}
}

func (x *AccountInfoStringData) GetRequestedValue() string {
	if x != nil {
		return x.RequestedValue
	}
	return ""
}

var File_mt5_term_api_account_information_proto protoreflect.FileDescriptor

var file_mt5_term_api_account_information_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x74, 0x35, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2d, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x6d, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x74, 0x35, 0x2d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x18, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x6d, 0x74,
	0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x49, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6a, 0x0a, 0x19, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4d, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49,
	0x64, 0x22, 0x8e, 0x01, 0x0a, 0x17, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x74,
	0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x41, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x68, 0x0a, 0x18, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x4c, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x64, 0x22,
	0x8c, 0x01, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40,
	0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x2a, 0xf6, 0x02, 0x0a, 0x1d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x42, 0x41,
	0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x41,
	0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x54, 0x10, 0x02, 0x12,
	0x12, 0x0a, 0x0e, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x54,
	0x59, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4d,
	0x41, 0x52, 0x47, 0x49, 0x4e, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x5f, 0x46, 0x52, 0x45, 0x45, 0x10, 0x05,
	0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47,
	0x49, 0x4e, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x10, 0x06, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x4f, 0x5f,
	0x43, 0x41, 0x4c, 0x4c, 0x10, 0x07, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x4f, 0x5f, 0x53, 0x4f, 0x10, 0x08,
	0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47,
	0x49, 0x4e, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x09, 0x12, 0x1e, 0x0a, 0x1a,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x5f, 0x4d,
	0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x0a, 0x12, 0x12, 0x0a, 0x0e,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x53, 0x53, 0x45, 0x54, 0x53, 0x10, 0x0b,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x41, 0x42,
	0x49, 0x4c, 0x49, 0x54, 0x49, 0x45, 0x53, 0x10, 0x0c, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x43, 0x43,
	0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x0d, 0x2a, 0xb5, 0x02, 0x0a, 0x1e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x44, 0x45,
	0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x52, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x18, 0x0a,
	0x14, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x53, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x5f, 0x53, 0x4f, 0x5f, 0x4d, 0x4f, 0x44,
	0x45, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54,
	0x52, 0x41, 0x44, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44, 0x10, 0x05, 0x12, 0x18,
	0x0a, 0x14, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f,
	0x45, 0x58, 0x50, 0x45, 0x52, 0x54, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x43, 0x4f,
	0x55, 0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x47, 0x49, 0x4e, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10,
	0x07, 0x12, 0x1b, 0x0a, 0x17, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x43, 0x55, 0x52,
	0x52, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x44, 0x49, 0x47, 0x49, 0x54, 0x53, 0x10, 0x08, 0x12, 0x16,
	0x0a, 0x12, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x46, 0x49, 0x46, 0x4f, 0x5f, 0x43,
	0x4c, 0x4f, 0x53, 0x45, 0x10, 0x09, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x5f, 0x48, 0x45, 0x44, 0x47, 0x45, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44, 0x10,
	0x0a, 0x2a, 0x70, 0x0a, 0x1d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4e, 0x41,
	0x4d, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x43, 0x43, 0x4f,
	0x55, 0x4e, 0x54, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x43, 0x59, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x41, 0x4e,
	0x59, 0x10, 0x03, 0x32, 0x96, 0x03, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x7d, 0x0a, 0x11, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12,
	0x26, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x12, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x12, 0x27, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x7d, 0x0a,
	0x11, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x26, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x74, 0x35,
	0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x42, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x2e, 0x6d, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x72, 0x6f, 0x6f,
	0x74, 0x2f, 0x6d, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x69, 0x74,
	0x2f, 0x6d, 0x74, 0x35, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67,
	0x6f, 0xaa, 0x02, 0x0c, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mt5_term_api_account_information_proto_rawDescOnce sync.Once
	file_mt5_term_api_account_information_proto_rawDescData = file_mt5_term_api_account_information_proto_rawDesc
)

func file_mt5_term_api_account_information_proto_rawDescGZIP() []byte {
	file_mt5_term_api_account_information_proto_rawDescOnce.Do(func() {
		file_mt5_term_api_account_information_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt5_term_api_account_information_proto_rawDescData)
	})
	return file_mt5_term_api_account_information_proto_rawDescData
}

var file_mt5_term_api_account_information_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mt5_term_api_account_information_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mt5_term_api_account_information_proto_goTypes = []interface{}{
	(AccountInfoDoublePropertyType)(0),  // 0: mt5_term_api.AccountInfoDoublePropertyType
	(AccountInfoIntegerPropertyType)(0), // 1: mt5_term_api.AccountInfoIntegerPropertyType
	(AccountInfoStringPropertyType)(0),  // 2: mt5_term_api.AccountInfoStringPropertyType
	(*AccountInfoDoubleRequest)(nil),    // 3: mt5_term_api.AccountInfoDoubleRequest
	(*AccountInfoDoubleReply)(nil),      // 4: mt5_term_api.AccountInfoDoubleReply
	(*AccountInfoDoubleData)(nil),       // 5: mt5_term_api.AccountInfoDoubleData
	(*AccountInfoIntegerRequest)(nil),   // 6: mt5_term_api.AccountInfoIntegerRequest
	(*AccountInfoIntegerReply)(nil),     // 7: mt5_term_api.AccountInfoIntegerReply
	(*AccountInfoIntegerData)(nil),      // 8: mt5_term_api.AccountInfoIntegerData
	(*AccountInfoStringRequest)(nil),    // 9: mt5_term_api.AccountInfoStringRequest
	(*AccountInfoStringReply)(nil),      // 10: mt5_term_api.AccountInfoStringReply
	(*AccountInfoStringData)(nil),       // 11: mt5_term_api.AccountInfoStringData
	(*Error)(nil),                       // 12: mt5_term_api.Error
}
var file_mt5_term_api_account_information_proto_depIdxs = []int32{
	0,  // 0: mt5_term_api.AccountInfoDoubleRequest.property_id:type_name -> mt5_term_api.AccountInfoDoublePropertyType
	5,  // 1: mt5_term_api.AccountInfoDoubleReply.data:type_name -> mt5_term_api.AccountInfoDoubleData
	12, // 2: mt5_term_api.AccountInfoDoubleReply.error:type_name -> mt5_term_api.Error
	1,  // 3: mt5_term_api.AccountInfoIntegerRequest.property_id:type_name -> mt5_term_api.AccountInfoIntegerPropertyType
	8,  // 4: mt5_term_api.AccountInfoIntegerReply.data:type_name -> mt5_term_api.AccountInfoIntegerData
	12, // 5: mt5_term_api.AccountInfoIntegerReply.error:type_name -> mt5_term_api.Error
	2,  // 6: mt5_term_api.AccountInfoStringRequest.property_id:type_name -> mt5_term_api.AccountInfoStringPropertyType
	11, // 7: mt5_term_api.AccountInfoStringReply.data:type_name -> mt5_term_api.AccountInfoStringData
	12, // 8: mt5_term_api.AccountInfoStringReply.error:type_name -> mt5_term_api.Error
	3,  // 9: mt5_term_api.AccountInformation.AccountInfoDouble:input_type -> mt5_term_api.AccountInfoDoubleRequest
	6,  // 10: mt5_term_api.AccountInformation.AccountInfoInteger:input_type -> mt5_term_api.AccountInfoIntegerRequest
	9,  // 11: mt5_term_api.AccountInformation.AccountInfoString:input_type -> mt5_term_api.AccountInfoStringRequest
	4,  // 12: mt5_term_api.AccountInformation.AccountInfoDouble:output_type -> mt5_term_api.AccountInfoDoubleReply
	7,  // 13: mt5_term_api.AccountInformation.AccountInfoInteger:output_type -> mt5_term_api.AccountInfoIntegerReply
	10, // 14: mt5_term_api.AccountInformation.AccountInfoString:output_type -> mt5_term_api.AccountInfoStringReply
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mt5_term_api_account_information_proto_init() }
func file_mt5_term_api_account_information_proto_init() {
	if File_mt5_term_api_account_information_proto != nil {
		return
	}
	file_mrpc_mt5_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mt5_term_api_account_information_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoDoubleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoDoubleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoDoubleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoIntegerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoIntegerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoIntegerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoStringReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_account_information_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoStringData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mt5_term_api_account_information_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AccountInfoDoubleReply_Data)(nil),
		(*AccountInfoDoubleReply_Error)(nil),
	}
	file_mt5_term_api_account_information_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*AccountInfoIntegerReply_Data)(nil),
		(*AccountInfoIntegerReply_Error)(nil),
	}
	file_mt5_term_api_account_information_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*AccountInfoStringReply_Data)(nil),
		(*AccountInfoStringReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt5_term_api_account_information_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt5_term_api_account_information_proto_goTypes,
		DependencyIndexes: file_mt5_term_api_account_information_proto_depIdxs,
		EnumInfos:         file_mt5_term_api_account_information_proto_enumTypes,
		MessageInfos:      file_mt5_term_api_account_information_proto_msgTypes,
	}.Build()
	File_mt5_term_api_account_information_proto = out.File
	file_mt5_term_api_account_information_proto_rawDesc = nil
	file_mt5_term_api_account_information_proto_goTypes = nil
	file_mt5_term_api_account_information_proto_depIdxs = nil
}
