// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-demo-account.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemoAccountClient is the client API for DemoAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoAccountClient interface {
	// Open a demo account. Full wizard flow: search → select → fill form → register.
	// Returns login, password, and investor password for the new demo account.
	// [DefaultValues]
	//
	//	{
	//	  "company": "MetaQuotes Ltd.",
	//	  "firstName": "Test",
	//	  "lastName": "User",
	//	  "email": "test@test.com",
	//	  "phone": "+1234567890",
	//	  "timeoutSeconds": "60"
	//	}
	OpenDemoAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error)
	// Interactive step-by-step demo account opening wizard.
	// Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
	DemoOpenAccountInteractive(ctx context.Context, opts ...grpc.CallOption) (DemoAccount_DemoOpenAccountInteractiveClient, error)
}

type demoAccountClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoAccountClient(cc grpc.ClientConnInterface) DemoAccountClient {
	return &demoAccountClient{cc}
}

func (c *demoAccountClient) OpenDemoAccount(ctx context.Context, in *GuiDemoOpenAccountRequest, opts ...grpc.CallOption) (*GuiDemoOpenAccountReply, error) {
	out := new(GuiDemoOpenAccountReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.DemoAccount/OpenDemoAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoAccountClient) DemoOpenAccountInteractive(ctx context.Context, opts ...grpc.CallOption) (DemoAccount_DemoOpenAccountInteractiveClient, error) {
	stream, err := c.cc.NewStream(ctx, &DemoAccount_ServiceDesc.Streams[0], "/mt5_term_api.DemoAccount/DemoOpenAccountInteractive", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoAccountDemoOpenAccountInteractiveClient{stream}
	return x, nil
}

type DemoAccount_DemoOpenAccountInteractiveClient interface {
	Send(*GuiDemoInteractiveClientMessage) error
	Recv() (*GuiDemoInteractiveServerMessage, error)
	grpc.ClientStream
}

type demoAccountDemoOpenAccountInteractiveClient struct {
	grpc.ClientStream
}

func (x *demoAccountDemoOpenAccountInteractiveClient) Send(m *GuiDemoInteractiveClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *demoAccountDemoOpenAccountInteractiveClient) Recv() (*GuiDemoInteractiveServerMessage, error) {
	m := new(GuiDemoInteractiveServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoAccountServer is the server API for DemoAccount service.
// All implementations should embed UnimplementedDemoAccountServer
// for forward compatibility
type DemoAccountServer interface {
	// Open a demo account. Full wizard flow: search → select → fill form → register.
	// Returns login, password, and investor password for the new demo account.
	// [DefaultValues]
	//
	//	{
	//	  "company": "MetaQuotes Ltd.",
	//	  "firstName": "Test",
	//	  "lastName": "User",
	//	  "email": "test@test.com",
	//	  "phone": "+1234567890",
	//	  "timeoutSeconds": "60"
	//	}
	OpenDemoAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error)
	// Interactive step-by-step demo account opening wizard.
	// Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
	DemoOpenAccountInteractive(DemoAccount_DemoOpenAccountInteractiveServer) error
}

// UnimplementedDemoAccountServer should be embedded to have forward compatible implementations.
type UnimplementedDemoAccountServer struct {
}

func (UnimplementedDemoAccountServer) OpenDemoAccount(context.Context, *GuiDemoOpenAccountRequest) (*GuiDemoOpenAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenDemoAccount not implemented")
}
func (UnimplementedDemoAccountServer) DemoOpenAccountInteractive(DemoAccount_DemoOpenAccountInteractiveServer) error {
	return status.Errorf(codes.Unimplemented, "method DemoOpenAccountInteractive not implemented")
}

// UnsafeDemoAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoAccountServer will
// result in compilation errors.
type UnsafeDemoAccountServer interface {
	mustEmbedUnimplementedDemoAccountServer()
}

func RegisterDemoAccountServer(s grpc.ServiceRegistrar, srv DemoAccountServer) {
	s.RegisterService(&DemoAccount_ServiceDesc, srv)
}

func _DemoAccount_OpenDemoAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuiDemoOpenAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoAccountServer).OpenDemoAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.DemoAccount/OpenDemoAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoAccountServer).OpenDemoAccount(ctx, req.(*GuiDemoOpenAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemoAccount_DemoOpenAccountInteractive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DemoAccountServer).DemoOpenAccountInteractive(&demoAccountDemoOpenAccountInteractiveServer{stream})
}

type DemoAccount_DemoOpenAccountInteractiveServer interface {
	Send(*GuiDemoInteractiveServerMessage) error
	Recv() (*GuiDemoInteractiveClientMessage, error)
	grpc.ServerStream
}

type demoAccountDemoOpenAccountInteractiveServer struct {
	grpc.ServerStream
}

func (x *demoAccountDemoOpenAccountInteractiveServer) Send(m *GuiDemoInteractiveServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *demoAccountDemoOpenAccountInteractiveServer) Recv() (*GuiDemoInteractiveClientMessage, error) {
	m := new(GuiDemoInteractiveClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoAccount_ServiceDesc is the grpc.ServiceDesc for DemoAccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoAccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.DemoAccount",
	HandlerType: (*DemoAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenDemoAccount",
			Handler:    _DemoAccount_OpenDemoAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DemoOpenAccountInteractive",
			Handler:       _DemoAccount_DemoOpenAccountInteractive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mt5-term-api-demo-account.proto",
}
