// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-connection.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnectionClient is the client API for Connection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionClient interface {
	// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it
	ConnectEx(ctx context.Context, in *ConnectExRequest, opts ...grpc.CallOption) (*ConnectExReply, error)
	// Creates terminal connection to the MT5 server and returns Guid of it
	// [DefaultValues]
	//
	//	{
	//	  "user": "21455",
	//	  "password": "1nJeS+Ae",
	//	  "host": "95.217.147.61",
	//	  "port": "443",
	//	  "baseChartSymbol": "EURUSD"
	//	}
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error)
	// Connect to account with user, password, host, port.
	// [DefaultValues]
	// {
	//
	//	 "user": "21455",
	//	 "password": "1nJeS+Ae",
	//	 "host": "95.217.147.61",
	//	 "port": "443",
	//	 "proxyUser": "ProxyUser123",
	//	 "proxyPassword": "qwerty123",
	//	 "proxyHost": "65.108.126.217",
	//	 "proxyPort": "1080",
	//	 "proxyType": "Socks5"
	//	}
	ConnectProxy(ctx context.Context, in *ConnectProxyRequest, opts ...grpc.CallOption) (*ConnectProxyReply, error)
	// Checks if terminal connection to MT5 server is alive
	CheckConnect(ctx context.Context, in *CheckConnectRequest, opts ...grpc.CallOption) (*CheckConnectReply, error)
	// Close terminal connection to MT5 server
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectReply, error)
	// If you need to recreate terminal instance with the same id
	Reconnect(ctx context.Context, in *ReconnectRequest, opts ...grpc.CallOption) (*ReconnectReply, error)
}

type connectionClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionClient(cc grpc.ClientConnInterface) ConnectionClient {
	return &connectionClient{cc}
}

func (c *connectionClient) ConnectEx(ctx context.Context, in *ConnectExRequest, opts ...grpc.CallOption) (*ConnectExReply, error) {
	out := new(ConnectExReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Connection/ConnectEx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error) {
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Connection/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) ConnectProxy(ctx context.Context, in *ConnectProxyRequest, opts ...grpc.CallOption) (*ConnectProxyReply, error) {
	out := new(ConnectProxyReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Connection/ConnectProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) CheckConnect(ctx context.Context, in *CheckConnectRequest, opts ...grpc.CallOption) (*CheckConnectReply, error) {
	out := new(CheckConnectReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Connection/CheckConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectReply, error) {
	out := new(DisconnectReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Connection/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Reconnect(ctx context.Context, in *ReconnectRequest, opts ...grpc.CallOption) (*ReconnectReply, error) {
	out := new(ReconnectReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.Connection/Reconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServer is the server API for Connection service.
// All implementations should embed UnimplementedConnectionServer
// for forward compatibility
type ConnectionServer interface {
	// Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it
	ConnectEx(context.Context, *ConnectExRequest) (*ConnectExReply, error)
	// Creates terminal connection to the MT5 server and returns Guid of it
	// [DefaultValues]
	//
	//	{
	//	  "user": "21455",
	//	  "password": "1nJeS+Ae",
	//	  "host": "95.217.147.61",
	//	  "port": "443",
	//	  "baseChartSymbol": "EURUSD"
	//	}
	Connect(context.Context, *ConnectRequest) (*ConnectReply, error)
	// Connect to account with user, password, host, port.
	// [DefaultValues]
	// {
	//
	//	 "user": "21455",
	//	 "password": "1nJeS+Ae",
	//	 "host": "95.217.147.61",
	//	 "port": "443",
	//	 "proxyUser": "ProxyUser123",
	//	 "proxyPassword": "qwerty123",
	//	 "proxyHost": "65.108.126.217",
	//	 "proxyPort": "1080",
	//	 "proxyType": "Socks5"
	//	}
	ConnectProxy(context.Context, *ConnectProxyRequest) (*ConnectProxyReply, error)
	// Checks if terminal connection to MT5 server is alive
	CheckConnect(context.Context, *CheckConnectRequest) (*CheckConnectReply, error)
	// Close terminal connection to MT5 server
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectReply, error)
	// If you need to recreate terminal instance with the same id
	Reconnect(context.Context, *ReconnectRequest) (*ReconnectReply, error)
}

// UnimplementedConnectionServer should be embedded to have forward compatible implementations.
type UnimplementedConnectionServer struct {
}

func (UnimplementedConnectionServer) ConnectEx(context.Context, *ConnectExRequest) (*ConnectExReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectEx not implemented")
}
func (UnimplementedConnectionServer) Connect(context.Context, *ConnectRequest) (*ConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConnectionServer) ConnectProxy(context.Context, *ConnectProxyRequest) (*ConnectProxyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectProxy not implemented")
}
func (UnimplementedConnectionServer) CheckConnect(context.Context, *CheckConnectRequest) (*CheckConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckConnect not implemented")
}
func (UnimplementedConnectionServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedConnectionServer) Reconnect(context.Context, *ReconnectRequest) (*ReconnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reconnect not implemented")
}

// UnsafeConnectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServer will
// result in compilation errors.
type UnsafeConnectionServer interface {
	mustEmbedUnimplementedConnectionServer()
}

func RegisterConnectionServer(s grpc.ServiceRegistrar, srv ConnectionServer) {
	s.RegisterService(&Connection_ServiceDesc, srv)
}

func _Connection_ConnectEx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectExRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).ConnectEx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Connection/ConnectEx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).ConnectEx(ctx, req.(*ConnectExRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Connection/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_ConnectProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).ConnectProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Connection/ConnectProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).ConnectProxy(ctx, req.(*ConnectProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_CheckConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).CheckConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Connection/CheckConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).CheckConnect(ctx, req.(*CheckConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Connection/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Reconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Reconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.Connection/Reconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Reconnect(ctx, req.(*ReconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Connection_ServiceDesc is the grpc.ServiceDesc for Connection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Connection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.Connection",
	HandlerType: (*ConnectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectEx",
			Handler:    _Connection_ConnectEx_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Connection_Connect_Handler,
		},
		{
			MethodName: "ConnectProxy",
			Handler:    _Connection_ConnectProxy_Handler,
		},
		{
			MethodName: "CheckConnect",
			Handler:    _Connection_CheckConnect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Connection_Disconnect_Handler,
		},
		{
			MethodName: "Reconnect",
			Handler:    _Connection_Reconnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-connection.proto",
}
