// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-subscriptions.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	OnSymbolTick(ctx context.Context, in *OnSymbolTickRequest, opts ...grpc.CallOption) (SubscriptionService_OnSymbolTickClient, error)
	OnTrade(ctx context.Context, in *OnTradeRequest, opts ...grpc.CallOption) (SubscriptionService_OnTradeClient, error)
	OnPositionProfit(ctx context.Context, in *OnPositionProfitRequest, opts ...grpc.CallOption) (SubscriptionService_OnPositionProfitClient, error)
	OnPositionsAndPendingOrdersTickets(ctx context.Context, in *OnPositionsAndPendingOrdersTicketsRequest, opts ...grpc.CallOption) (SubscriptionService_OnPositionsAndPendingOrdersTicketsClient, error)
	OnTradeTransaction(ctx context.Context, in *OnTradeTransactionRequest, opts ...grpc.CallOption) (SubscriptionService_OnTradeTransactionClient, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) OnSymbolTick(ctx context.Context, in *OnSymbolTickRequest, opts ...grpc.CallOption) (SubscriptionService_OnSymbolTickClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[0], "/mt5_term_api.SubscriptionService/OnSymbolTick", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnSymbolTickClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnSymbolTickClient interface {
	Recv() (*OnSymbolTickReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnSymbolTickClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnSymbolTickClient) Recv() (*OnSymbolTickReply, error) {
	m := new(OnSymbolTickReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnTrade(ctx context.Context, in *OnTradeRequest, opts ...grpc.CallOption) (SubscriptionService_OnTradeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[1], "/mt5_term_api.SubscriptionService/OnTrade", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnTradeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnTradeClient interface {
	Recv() (*OnTradeReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnTradeClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnTradeClient) Recv() (*OnTradeReply, error) {
	m := new(OnTradeReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnPositionProfit(ctx context.Context, in *OnPositionProfitRequest, opts ...grpc.CallOption) (SubscriptionService_OnPositionProfitClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[2], "/mt5_term_api.SubscriptionService/OnPositionProfit", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnPositionProfitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnPositionProfitClient interface {
	Recv() (*OnPositionProfitReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnPositionProfitClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnPositionProfitClient) Recv() (*OnPositionProfitReply, error) {
	m := new(OnPositionProfitReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnPositionsAndPendingOrdersTickets(ctx context.Context, in *OnPositionsAndPendingOrdersTicketsRequest, opts ...grpc.CallOption) (SubscriptionService_OnPositionsAndPendingOrdersTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[3], "/mt5_term_api.SubscriptionService/OnPositionsAndPendingOrdersTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnPositionsAndPendingOrdersTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnPositionsAndPendingOrdersTicketsClient interface {
	Recv() (*OnPositionsAndPendingOrdersTicketsReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnPositionsAndPendingOrdersTicketsClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnPositionsAndPendingOrdersTicketsClient) Recv() (*OnPositionsAndPendingOrdersTicketsReply, error) {
	m := new(OnPositionsAndPendingOrdersTicketsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) OnTradeTransaction(ctx context.Context, in *OnTradeTransactionRequest, opts ...grpc.CallOption) (SubscriptionService_OnTradeTransactionClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[4], "/mt5_term_api.SubscriptionService/OnTradeTransaction", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceOnTradeTransactionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_OnTradeTransactionClient interface {
	Recv() (*OnTradeTransactionReply, error)
	grpc.ClientStream
}

type subscriptionServiceOnTradeTransactionClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceOnTradeTransactionClient) Recv() (*OnTradeTransactionReply, error) {
	m := new(OnTradeTransactionReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations should embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	OnSymbolTick(*OnSymbolTickRequest, SubscriptionService_OnSymbolTickServer) error
	OnTrade(*OnTradeRequest, SubscriptionService_OnTradeServer) error
	OnPositionProfit(*OnPositionProfitRequest, SubscriptionService_OnPositionProfitServer) error
	OnPositionsAndPendingOrdersTickets(*OnPositionsAndPendingOrdersTicketsRequest, SubscriptionService_OnPositionsAndPendingOrdersTicketsServer) error
	OnTradeTransaction(*OnTradeTransactionRequest, SubscriptionService_OnTradeTransactionServer) error
}

// UnimplementedSubscriptionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) OnSymbolTick(*OnSymbolTickRequest, SubscriptionService_OnSymbolTickServer) error {
	return status.Errorf(codes.Unimplemented, "method OnSymbolTick not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnTrade(*OnTradeRequest, SubscriptionService_OnTradeServer) error {
	return status.Errorf(codes.Unimplemented, "method OnTrade not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnPositionProfit(*OnPositionProfitRequest, SubscriptionService_OnPositionProfitServer) error {
	return status.Errorf(codes.Unimplemented, "method OnPositionProfit not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnPositionsAndPendingOrdersTickets(*OnPositionsAndPendingOrdersTicketsRequest, SubscriptionService_OnPositionsAndPendingOrdersTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method OnPositionsAndPendingOrdersTickets not implemented")
}
func (UnimplementedSubscriptionServiceServer) OnTradeTransaction(*OnTradeTransactionRequest, SubscriptionService_OnTradeTransactionServer) error {
	return status.Errorf(codes.Unimplemented, "method OnTradeTransaction not implemented")
}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_OnSymbolTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnSymbolTickRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnSymbolTick(m, &subscriptionServiceOnSymbolTickServer{stream})
}

type SubscriptionService_OnSymbolTickServer interface {
	Send(*OnSymbolTickReply) error
	grpc.ServerStream
}

type subscriptionServiceOnSymbolTickServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnSymbolTickServer) Send(m *OnSymbolTickReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnTrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnTradeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnTrade(m, &subscriptionServiceOnTradeServer{stream})
}

type SubscriptionService_OnTradeServer interface {
	Send(*OnTradeReply) error
	grpc.ServerStream
}

type subscriptionServiceOnTradeServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnTradeServer) Send(m *OnTradeReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnPositionProfit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnPositionProfitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnPositionProfit(m, &subscriptionServiceOnPositionProfitServer{stream})
}

type SubscriptionService_OnPositionProfitServer interface {
	Send(*OnPositionProfitReply) error
	grpc.ServerStream
}

type subscriptionServiceOnPositionProfitServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnPositionProfitServer) Send(m *OnPositionProfitReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnPositionsAndPendingOrdersTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnPositionsAndPendingOrdersTicketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnPositionsAndPendingOrdersTickets(m, &subscriptionServiceOnPositionsAndPendingOrdersTicketsServer{stream})
}

type SubscriptionService_OnPositionsAndPendingOrdersTicketsServer interface {
	Send(*OnPositionsAndPendingOrdersTicketsReply) error
	grpc.ServerStream
}

type subscriptionServiceOnPositionsAndPendingOrdersTicketsServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnPositionsAndPendingOrdersTicketsServer) Send(m *OnPositionsAndPendingOrdersTicketsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_OnTradeTransaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OnTradeTransactionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).OnTradeTransaction(m, &subscriptionServiceOnTradeTransactionServer{stream})
}

type SubscriptionService_OnTradeTransactionServer interface {
	Send(*OnTradeTransactionReply) error
	grpc.ServerStream
}

type subscriptionServiceOnTradeTransactionServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceOnTradeTransactionServer) Send(m *OnTradeTransactionReply) error {
	return x.ServerStream.SendMsg(m)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnSymbolTick",
			Handler:       _SubscriptionService_OnSymbolTick_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnTrade",
			Handler:       _SubscriptionService_OnTrade_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnPositionProfit",
			Handler:       _SubscriptionService_OnPositionProfit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnPositionsAndPendingOrdersTickets",
			Handler:       _SubscriptionService_OnPositionsAndPendingOrdersTickets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnTradeTransaction",
			Handler:       _SubscriptionService_OnTradeTransaction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mt5-term-api-subscriptions.proto",
}
