// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-vnc.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VncServiceClient is the client API for VncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VncServiceClient interface {
	// Bidirectional stream: raw VNC (RFB) binary data flows in both directions
	VncStream(ctx context.Context, opts ...grpc.CallOption) (VncService_VncStreamClient, error)
}

type vncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVncServiceClient(cc grpc.ClientConnInterface) VncServiceClient {
	return &vncServiceClient{cc}
}

func (c *vncServiceClient) VncStream(ctx context.Context, opts ...grpc.CallOption) (VncService_VncStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &VncService_ServiceDesc.Streams[0], "/mt5_term_api.VncService/VncStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &vncServiceVncStreamClient{stream}
	return x, nil
}

type VncService_VncStreamClient interface {
	Send(*VncData) error
	Recv() (*VncData, error)
	grpc.ClientStream
}

type vncServiceVncStreamClient struct {
	grpc.ClientStream
}

func (x *vncServiceVncStreamClient) Send(m *VncData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vncServiceVncStreamClient) Recv() (*VncData, error) {
	m := new(VncData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VncServiceServer is the server API for VncService service.
// All implementations should embed UnimplementedVncServiceServer
// for forward compatibility
type VncServiceServer interface {
	// Bidirectional stream: raw VNC (RFB) binary data flows in both directions
	VncStream(VncService_VncStreamServer) error
}

// UnimplementedVncServiceServer should be embedded to have forward compatible implementations.
type UnimplementedVncServiceServer struct {
}

func (UnimplementedVncServiceServer) VncStream(VncService_VncStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method VncStream not implemented")
}

// UnsafeVncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VncServiceServer will
// result in compilation errors.
type UnsafeVncServiceServer interface {
	mustEmbedUnimplementedVncServiceServer()
}

func RegisterVncServiceServer(s grpc.ServiceRegistrar, srv VncServiceServer) {
	s.RegisterService(&VncService_ServiceDesc, srv)
}

func _VncService_VncStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VncServiceServer).VncStream(&vncServiceVncStreamServer{stream})
}

type VncService_VncStreamServer interface {
	Send(*VncData) error
	Recv() (*VncData, error)
	grpc.ServerStream
}

type vncServiceVncStreamServer struct {
	grpc.ServerStream
}

func (x *vncServiceVncStreamServer) Send(m *VncData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vncServiceVncStreamServer) Recv() (*VncData, error) {
	m := new(VncData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VncService_ServiceDesc is the grpc.ServiceDesc for VncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.VncService",
	HandlerType: (*VncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VncStream",
			Handler:       _VncService_VncStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mt5-term-api-vnc.proto",
}
