// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: mt5-term-api-account-information.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountInformationClient is the client API for AccountInformation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountInformationClient interface {
	// Returns the double value of the corresponding account property
	// https://www.mql5.com/en/docs/account/accountinfodouble
	AccountInfoDouble(ctx context.Context, in *AccountInfoDoubleRequest, opts ...grpc.CallOption) (*AccountInfoDoubleReply, error)
	// Returns the value of the properties of the account
	// https://www.mql5.com/en/docs/account/accountinfointeger
	AccountInfoInteger(ctx context.Context, in *AccountInfoIntegerRequest, opts ...grpc.CallOption) (*AccountInfoIntegerReply, error)
	// Returns the value of the appropriate account property
	// https://www.mql5.com/en/docs/account/accountinfostring
	AccountInfoString(ctx context.Context, in *AccountInfoStringRequest, opts ...grpc.CallOption) (*AccountInfoStringReply, error)
}

type accountInformationClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountInformationClient(cc grpc.ClientConnInterface) AccountInformationClient {
	return &accountInformationClient{cc}
}

func (c *accountInformationClient) AccountInfoDouble(ctx context.Context, in *AccountInfoDoubleRequest, opts ...grpc.CallOption) (*AccountInfoDoubleReply, error) {
	out := new(AccountInfoDoubleReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.AccountInformation/AccountInfoDouble", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountInformationClient) AccountInfoInteger(ctx context.Context, in *AccountInfoIntegerRequest, opts ...grpc.CallOption) (*AccountInfoIntegerReply, error) {
	out := new(AccountInfoIntegerReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.AccountInformation/AccountInfoInteger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountInformationClient) AccountInfoString(ctx context.Context, in *AccountInfoStringRequest, opts ...grpc.CallOption) (*AccountInfoStringReply, error) {
	out := new(AccountInfoStringReply)
	err := c.cc.Invoke(ctx, "/mt5_term_api.AccountInformation/AccountInfoString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountInformationServer is the server API for AccountInformation service.
// All implementations should embed UnimplementedAccountInformationServer
// for forward compatibility
type AccountInformationServer interface {
	// Returns the double value of the corresponding account property
	// https://www.mql5.com/en/docs/account/accountinfodouble
	AccountInfoDouble(context.Context, *AccountInfoDoubleRequest) (*AccountInfoDoubleReply, error)
	// Returns the value of the properties of the account
	// https://www.mql5.com/en/docs/account/accountinfointeger
	AccountInfoInteger(context.Context, *AccountInfoIntegerRequest) (*AccountInfoIntegerReply, error)
	// Returns the value of the appropriate account property
	// https://www.mql5.com/en/docs/account/accountinfostring
	AccountInfoString(context.Context, *AccountInfoStringRequest) (*AccountInfoStringReply, error)
}

// UnimplementedAccountInformationServer should be embedded to have forward compatible implementations.
type UnimplementedAccountInformationServer struct {
}

func (UnimplementedAccountInformationServer) AccountInfoDouble(context.Context, *AccountInfoDoubleRequest) (*AccountInfoDoubleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInfoDouble not implemented")
}
func (UnimplementedAccountInformationServer) AccountInfoInteger(context.Context, *AccountInfoIntegerRequest) (*AccountInfoIntegerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInfoInteger not implemented")
}
func (UnimplementedAccountInformationServer) AccountInfoString(context.Context, *AccountInfoStringRequest) (*AccountInfoStringReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInfoString not implemented")
}

// UnsafeAccountInformationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountInformationServer will
// result in compilation errors.
type UnsafeAccountInformationServer interface {
	mustEmbedUnimplementedAccountInformationServer()
}

func RegisterAccountInformationServer(s grpc.ServiceRegistrar, srv AccountInformationServer) {
	s.RegisterService(&AccountInformation_ServiceDesc, srv)
}

func _AccountInformation_AccountInfoDouble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfoDoubleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServer).AccountInfoDouble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.AccountInformation/AccountInfoDouble",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServer).AccountInfoDouble(ctx, req.(*AccountInfoDoubleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountInformation_AccountInfoInteger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfoIntegerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServer).AccountInfoInteger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.AccountInformation/AccountInfoInteger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServer).AccountInfoInteger(ctx, req.(*AccountInfoIntegerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountInformation_AccountInfoString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfoStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServer).AccountInfoString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mt5_term_api.AccountInformation/AccountInfoString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServer).AccountInfoString(ctx, req.(*AccountInfoStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountInformation_ServiceDesc is the grpc.ServiceDesc for AccountInformation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountInformation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mt5_term_api.AccountInformation",
	HandlerType: (*AccountInformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountInfoDouble",
			Handler:    _AccountInformation_AccountInfoDouble_Handler,
		},
		{
			MethodName: "AccountInfoInteger",
			Handler:    _AccountInformation_AccountInfoInteger_Handler,
		},
		{
			MethodName: "AccountInfoString",
			Handler:    _AccountInformation_AccountInfoString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mt5-term-api-account-information.proto",
}
