// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mt5-term-api-trade-functions.proto

package _go

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ENUM_ORDER_TYPE_TF int32

const (
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY             ENUM_ORDER_TYPE_TF = 0 // Market Buy order
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_SELL            ENUM_ORDER_TYPE_TF = 1 // Market Sell order
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY_LIMIT       ENUM_ORDER_TYPE_TF = 2 // Buy Limit pending order
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_SELL_LIMIT      ENUM_ORDER_TYPE_TF = 3 // Sell Limit pending order
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY_STOP        ENUM_ORDER_TYPE_TF = 4 // Buy Stop pending order
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_SELL_STOP       ENUM_ORDER_TYPE_TF = 5 // Sell Stop pending order
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY_STOP_LIMIT  ENUM_ORDER_TYPE_TF = 6 // Upon reaching the order price, a pending Buy Limit order is placed at the StopLimit price
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_SELL_STOP_LIMIT ENUM_ORDER_TYPE_TF = 7 // Upon reaching the order price, a pending Sell Limit order is placed at the StopLimit price
	ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_CLOSE_BY        ENUM_ORDER_TYPE_TF = 8 // Order to close a position by an opposite one
)

// Enum value maps for ENUM_ORDER_TYPE_TF.
var (
	ENUM_ORDER_TYPE_TF_name = map[int32]string{
		0: "ORDER_TYPE_TF_BUY",
		1: "ORDER_TYPE_TF_SELL",
		2: "ORDER_TYPE_TF_BUY_LIMIT",
		3: "ORDER_TYPE_TF_SELL_LIMIT",
		4: "ORDER_TYPE_TF_BUY_STOP",
		5: "ORDER_TYPE_TF_SELL_STOP",
		6: "ORDER_TYPE_TF_BUY_STOP_LIMIT",
		7: "ORDER_TYPE_TF_SELL_STOP_LIMIT",
		8: "ORDER_TYPE_TF_CLOSE_BY",
	}
	ENUM_ORDER_TYPE_TF_value = map[string]int32{
		"ORDER_TYPE_TF_BUY":             0,
		"ORDER_TYPE_TF_SELL":            1,
		"ORDER_TYPE_TF_BUY_LIMIT":       2,
		"ORDER_TYPE_TF_SELL_LIMIT":      3,
		"ORDER_TYPE_TF_BUY_STOP":        4,
		"ORDER_TYPE_TF_SELL_STOP":       5,
		"ORDER_TYPE_TF_BUY_STOP_LIMIT":  6,
		"ORDER_TYPE_TF_SELL_STOP_LIMIT": 7,
		"ORDER_TYPE_TF_CLOSE_BY":        8,
	}
)

func (x ENUM_ORDER_TYPE_TF) Enum() *ENUM_ORDER_TYPE_TF {
	p := new(ENUM_ORDER_TYPE_TF)
	*p = x
	return p
}

func (x ENUM_ORDER_TYPE_TF) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENUM_ORDER_TYPE_TF) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_trade_functions_proto_enumTypes[0].Descriptor()
}

func (ENUM_ORDER_TYPE_TF) Type() protoreflect.EnumType {
	return &file_mt5_term_api_trade_functions_proto_enumTypes[0]
}

func (x ENUM_ORDER_TYPE_TF) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ENUM_ORDER_TYPE_TF.Descriptor instead.
func (ENUM_ORDER_TYPE_TF) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{0}
}

type MRPC_ENUM_TRADE_REQUEST_ACTIONS int32

const (
	// Place a trade order for an immediate execution with the specified parameters (market order)
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_DEAL MRPC_ENUM_TRADE_REQUEST_ACTIONS = 0
	// Place a trade order for the execution under specified conditions (pending order)
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_PENDING MRPC_ENUM_TRADE_REQUEST_ACTIONS = 1
	// Modify Stop Loss and Take Profit values of an opened position
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_SLTP MRPC_ENUM_TRADE_REQUEST_ACTIONS = 2
	// Modify the parameters of the order placed previously
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_MODIFY MRPC_ENUM_TRADE_REQUEST_ACTIONS = 3
	// Delete the pending order placed previously
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_REMOVE MRPC_ENUM_TRADE_REQUEST_ACTIONS = 4
	// Close a position by an opposite one
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_CLOSE_BY MRPC_ENUM_TRADE_REQUEST_ACTIONS = 5
)

// Enum value maps for MRPC_ENUM_TRADE_REQUEST_ACTIONS.
var (
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_name = map[int32]string{
		0: "TRADE_ACTION_DEAL",
		1: "TRADE_ACTION_PENDING",
		2: "TRADE_ACTION_SLTP",
		3: "TRADE_ACTION_MODIFY",
		4: "TRADE_ACTION_REMOVE",
		5: "TRADE_ACTION_CLOSE_BY",
	}
	MRPC_ENUM_TRADE_REQUEST_ACTIONS_value = map[string]int32{
		"TRADE_ACTION_DEAL":     0,
		"TRADE_ACTION_PENDING":  1,
		"TRADE_ACTION_SLTP":     2,
		"TRADE_ACTION_MODIFY":   3,
		"TRADE_ACTION_REMOVE":   4,
		"TRADE_ACTION_CLOSE_BY": 5,
	}
)

func (x MRPC_ENUM_TRADE_REQUEST_ACTIONS) Enum() *MRPC_ENUM_TRADE_REQUEST_ACTIONS {
	p := new(MRPC_ENUM_TRADE_REQUEST_ACTIONS)
	*p = x
	return p
}

func (x MRPC_ENUM_TRADE_REQUEST_ACTIONS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MRPC_ENUM_TRADE_REQUEST_ACTIONS) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_trade_functions_proto_enumTypes[1].Descriptor()
}

func (MRPC_ENUM_TRADE_REQUEST_ACTIONS) Type() protoreflect.EnumType {
	return &file_mt5_term_api_trade_functions_proto_enumTypes[1]
}

func (x MRPC_ENUM_TRADE_REQUEST_ACTIONS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MRPC_ENUM_TRADE_REQUEST_ACTIONS.Descriptor instead.
func (MRPC_ENUM_TRADE_REQUEST_ACTIONS) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{1}
}

type MRPC_ENUM_ORDER_TYPE_FILLING int32

const (
	// An order can be executed in the specified volume only. If the necessary amount of a financial instrument is currently unavailable in the market, the order will not be executed. The desired volume can be made up of several available offers. The possibility of using FOK orders is determined at the trade server.
	MRPC_ENUM_ORDER_TYPE_FILLING_ORDER_FILLING_FOK MRPC_ENUM_ORDER_TYPE_FILLING = 0
	// A trader agrees to execute a deal with the volume maximally available in the market within that indicated in the order. If the request cannot be filled completely, an order with the available volume will be executed, and the remaining volume will be canceled. The possibility of using IOC orders is determined at the trade server.
	MRPC_ENUM_ORDER_TYPE_FILLING_ORDER_FILLING_IOC MRPC_ENUM_ORDER_TYPE_FILLING = 1
	// The BoC order assumes that the order can only be placed in the Depth of Market and cannot be immediately executed. If the order can be executed immediately when placed, then it is canceled. In fact, the BOC policy guarantees that the price of the placed order will be worse than the current market. BoC orders are used to implement passive trading, so that the order is not executed immediately when placed and does not affect current liquidity. Only limit and stop limit orders are supported (ORDER_TYPE_BUY_LIMIT, ORDER_TYPE_SELL_LIMIT, ORDER_TYPE_BUY_STOP_LIMIT, ORDER_TYPE_SELL_STOP_LIMIT).
	MRPC_ENUM_ORDER_TYPE_FILLING_ORDER_FILLING_BOC MRPC_ENUM_ORDER_TYPE_FILLING = 3
	// In case of partial filling, an order with remaining volume is not canceled but processed further. Return orders are not allowed in the Market Execution mode (market execution — SYMBOL_TRADE_EXECUTION_MARKET).
	MRPC_ENUM_ORDER_TYPE_FILLING_ORDER_FILLING_RETURN MRPC_ENUM_ORDER_TYPE_FILLING = 2
)

// Enum value maps for MRPC_ENUM_ORDER_TYPE_FILLING.
var (
	MRPC_ENUM_ORDER_TYPE_FILLING_name = map[int32]string{
		0: "ORDER_FILLING_FOK",
		1: "ORDER_FILLING_IOC",
		3: "ORDER_FILLING_BOC",
		2: "ORDER_FILLING_RETURN",
	}
	MRPC_ENUM_ORDER_TYPE_FILLING_value = map[string]int32{
		"ORDER_FILLING_FOK":    0,
		"ORDER_FILLING_IOC":    1,
		"ORDER_FILLING_BOC":    3,
		"ORDER_FILLING_RETURN": 2,
	}
)

func (x MRPC_ENUM_ORDER_TYPE_FILLING) Enum() *MRPC_ENUM_ORDER_TYPE_FILLING {
	p := new(MRPC_ENUM_ORDER_TYPE_FILLING)
	*p = x
	return p
}

func (x MRPC_ENUM_ORDER_TYPE_FILLING) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MRPC_ENUM_ORDER_TYPE_FILLING) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_trade_functions_proto_enumTypes[2].Descriptor()
}

func (MRPC_ENUM_ORDER_TYPE_FILLING) Type() protoreflect.EnumType {
	return &file_mt5_term_api_trade_functions_proto_enumTypes[2]
}

func (x MRPC_ENUM_ORDER_TYPE_FILLING) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MRPC_ENUM_ORDER_TYPE_FILLING.Descriptor instead.
func (MRPC_ENUM_ORDER_TYPE_FILLING) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{2}
}

type MRPC_ENUM_ORDER_TYPE_TIME int32

const (
	// Good till cancel order
	MRPC_ENUM_ORDER_TYPE_TIME_ORDER_TIME_GTC MRPC_ENUM_ORDER_TYPE_TIME = 0
	// Good till current trade day order
	MRPC_ENUM_ORDER_TYPE_TIME_ORDER_TIME_DAY MRPC_ENUM_ORDER_TYPE_TIME = 1
	// Good till expired order
	MRPC_ENUM_ORDER_TYPE_TIME_ORDER_TIME_SPECIFIED MRPC_ENUM_ORDER_TYPE_TIME = 2
	// The order will be effective till 23:59:59 of the specified day. If this time is outside a trading session, the order expires in the nearest trading time.
	MRPC_ENUM_ORDER_TYPE_TIME_ORDER_TIME_SPECIFIED_DAY MRPC_ENUM_ORDER_TYPE_TIME = 3
)

// Enum value maps for MRPC_ENUM_ORDER_TYPE_TIME.
var (
	MRPC_ENUM_ORDER_TYPE_TIME_name = map[int32]string{
		0: "ORDER_TIME_GTC",
		1: "ORDER_TIME_DAY",
		2: "ORDER_TIME_SPECIFIED",
		3: "ORDER_TIME_SPECIFIED_DAY",
	}
	MRPC_ENUM_ORDER_TYPE_TIME_value = map[string]int32{
		"ORDER_TIME_GTC":           0,
		"ORDER_TIME_DAY":           1,
		"ORDER_TIME_SPECIFIED":     2,
		"ORDER_TIME_SPECIFIED_DAY": 3,
	}
)

func (x MRPC_ENUM_ORDER_TYPE_TIME) Enum() *MRPC_ENUM_ORDER_TYPE_TIME {
	p := new(MRPC_ENUM_ORDER_TYPE_TIME)
	*p = x
	return p
}

func (x MRPC_ENUM_ORDER_TYPE_TIME) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MRPC_ENUM_ORDER_TYPE_TIME) Descriptor() protoreflect.EnumDescriptor {
	return file_mt5_term_api_trade_functions_proto_enumTypes[3].Descriptor()
}

func (MRPC_ENUM_ORDER_TYPE_TIME) Type() protoreflect.EnumType {
	return &file_mt5_term_api_trade_functions_proto_enumTypes[3]
}

func (x MRPC_ENUM_ORDER_TYPE_TIME) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MRPC_ENUM_ORDER_TYPE_TIME.Descriptor instead.
func (MRPC_ENUM_ORDER_TYPE_TIME) EnumDescriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{3}
}

// 1. OrderCalcMargin
type OrderCalcMarginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string             `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                              // symbol name
	OrderType ENUM_ORDER_TYPE_TF `protobuf:"varint,2,opt,name=order_type,json=orderType,proto3,enum=mt5_term_api.ENUM_ORDER_TYPE_TF" json:"order_type,omitempty"` // type of order
	Volume    float64            `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`                                                            // Volume of the trade operation
	OpenPrice float64            `protobuf:"fixed64,4,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`                                     // Open price
}

func (x *OrderCalcMarginRequest) Reset() {
	*x = OrderCalcMarginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCalcMarginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCalcMarginRequest) ProtoMessage() {}

func (x *OrderCalcMarginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCalcMarginRequest.ProtoReflect.Descriptor instead.
func (*OrderCalcMarginRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCalcMarginRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderCalcMarginRequest) GetOrderType() ENUM_ORDER_TYPE_TF {
	if x != nil {
		return x.OrderType
	}
	return ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY
}

func (x *OrderCalcMarginRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OrderCalcMarginRequest) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

type OrderCalcMarginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*OrderCalcMarginReply_Data
	//	*OrderCalcMarginReply_Error
	Response isOrderCalcMarginReply_Response `protobuf_oneof:"response"`
}

func (x *OrderCalcMarginReply) Reset() {
	*x = OrderCalcMarginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCalcMarginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCalcMarginReply) ProtoMessage() {}

func (x *OrderCalcMarginReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCalcMarginReply.ProtoReflect.Descriptor instead.
func (*OrderCalcMarginReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{1}
}

func (m *OrderCalcMarginReply) GetResponse() isOrderCalcMarginReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *OrderCalcMarginReply) GetData() *OrderCalcMarginData {
	if x, ok := x.GetResponse().(*OrderCalcMarginReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *OrderCalcMarginReply) GetError() *Error {
	if x, ok := x.GetResponse().(*OrderCalcMarginReply_Error); ok {
		return x.Error
	}
	return nil
}

type isOrderCalcMarginReply_Response interface {
	isOrderCalcMarginReply_Response()
}

type OrderCalcMarginReply_Data struct {
	Data *OrderCalcMarginData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderCalcMarginReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderCalcMarginReply_Data) isOrderCalcMarginReply_Response() {}

func (*OrderCalcMarginReply_Error) isOrderCalcMarginReply_Response() {}

type OrderCalcMarginData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Margin float64 `protobuf:"fixed64,1,opt,name=margin,proto3" json:"margin,omitempty"` // The variable, to which the value of the required margin will be written in case the function is successfully executed. The calculation is performed as if there were no pending orders and open positions on the current account. The margin value depends on many factors, and can differ in different market environments.
}

func (x *OrderCalcMarginData) Reset() {
	*x = OrderCalcMarginData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCalcMarginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCalcMarginData) ProtoMessage() {}

func (x *OrderCalcMarginData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCalcMarginData.ProtoReflect.Descriptor instead.
func (*OrderCalcMarginData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCalcMarginData) GetMargin() float64 {
	if x != nil {
		return x.Margin
	}
	return 0
}

// 2. OrderCalcProfit
type OrderCalcProfitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderType  ENUM_ORDER_TYPE_TF `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3,enum=mt5_term_api.ENUM_ORDER_TYPE_TF" json:"order_type,omitempty"` // type of order
	Symbol     string             `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                              // symbol name
	Volume     float64            `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`                                                            // Volume of the trade operation
	OpenPrice  float64            `protobuf:"fixed64,4,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`                                     // Open price
	ClosePrice float64            `protobuf:"fixed64,5,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`                                  // Close price
}

func (x *OrderCalcProfitRequest) Reset() {
	*x = OrderCalcProfitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCalcProfitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCalcProfitRequest) ProtoMessage() {}

func (x *OrderCalcProfitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCalcProfitRequest.ProtoReflect.Descriptor instead.
func (*OrderCalcProfitRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCalcProfitRequest) GetOrderType() ENUM_ORDER_TYPE_TF {
	if x != nil {
		return x.OrderType
	}
	return ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY
}

func (x *OrderCalcProfitRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderCalcProfitRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OrderCalcProfitRequest) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *OrderCalcProfitRequest) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

type OrderCalcProfitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*OrderCalcProfitReply_Data
	//	*OrderCalcProfitReply_Error
	Response isOrderCalcProfitReply_Response `protobuf_oneof:"response"`
}

func (x *OrderCalcProfitReply) Reset() {
	*x = OrderCalcProfitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCalcProfitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCalcProfitReply) ProtoMessage() {}

func (x *OrderCalcProfitReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCalcProfitReply.ProtoReflect.Descriptor instead.
func (*OrderCalcProfitReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{4}
}

func (m *OrderCalcProfitReply) GetResponse() isOrderCalcProfitReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *OrderCalcProfitReply) GetData() *OrderCalcProfitData {
	if x, ok := x.GetResponse().(*OrderCalcProfitReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *OrderCalcProfitReply) GetError() *Error {
	if x, ok := x.GetResponse().(*OrderCalcProfitReply_Error); ok {
		return x.Error
	}
	return nil
}

type isOrderCalcProfitReply_Response interface {
	isOrderCalcProfitReply_Response()
}

type OrderCalcProfitReply_Data struct {
	Data *OrderCalcProfitData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderCalcProfitReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderCalcProfitReply_Data) isOrderCalcProfitReply_Response() {}

func (*OrderCalcProfitReply_Error) isOrderCalcProfitReply_Response() {}

type OrderCalcProfitData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profit float64 `protobuf:"fixed64,1,opt,name=profit,proto3" json:"profit,omitempty"` // The estimated profit value depends on many factors, and can differ in different market environments.
}

func (x *OrderCalcProfitData) Reset() {
	*x = OrderCalcProfitData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCalcProfitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCalcProfitData) ProtoMessage() {}

func (x *OrderCalcProfitData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCalcProfitData.ProtoReflect.Descriptor instead.
func (*OrderCalcProfitData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCalcProfitData) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

// 3. OrderCheck
type OrderCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MqlTradeRequest *MrpcMqlTradeRequest `protobuf:"bytes,1,opt,name=mql_trade_request,json=mqlTradeRequest,proto3" json:"mql_trade_request,omitempty"` // Interaction between the client terminal and a trade server for executing the order placing operation
}

func (x *OrderCheckRequest) Reset() {
	*x = OrderCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCheckRequest) ProtoMessage() {}

func (x *OrderCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCheckRequest.ProtoReflect.Descriptor instead.
func (*OrderCheckRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{6}
}

func (x *OrderCheckRequest) GetMqlTradeRequest() *MrpcMqlTradeRequest {
	if x != nil {
		return x.MqlTradeRequest
	}
	return nil
}

type OrderCheckReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*OrderCheckReply_Data
	//	*OrderCheckReply_Error
	Response isOrderCheckReply_Response `protobuf_oneof:"response"`
}

func (x *OrderCheckReply) Reset() {
	*x = OrderCheckReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCheckReply) ProtoMessage() {}

func (x *OrderCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCheckReply.ProtoReflect.Descriptor instead.
func (*OrderCheckReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{7}
}

func (m *OrderCheckReply) GetResponse() isOrderCheckReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *OrderCheckReply) GetData() *OrderCheckData {
	if x, ok := x.GetResponse().(*OrderCheckReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *OrderCheckReply) GetError() *Error {
	if x, ok := x.GetResponse().(*OrderCheckReply_Error); ok {
		return x.Error
	}
	return nil
}

type isOrderCheckReply_Response interface {
	isOrderCheckReply_Response()
}

type OrderCheckReply_Data struct {
	Data *OrderCheckData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type OrderCheckReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*OrderCheckReply_Data) isOrderCheckReply_Response() {}

func (*OrderCheckReply_Error) isOrderCheckReply_Response() {}

type OrderCheckData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MqlTradeCheckResult *MrpcMqlTradeCheckResult `protobuf:"bytes,1,opt,name=mql_trade_check_result,json=mqlTradeCheckResult,proto3" json:"mql_trade_check_result,omitempty"`
}

func (x *OrderCheckData) Reset() {
	*x = OrderCheckData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCheckData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCheckData) ProtoMessage() {}

func (x *OrderCheckData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCheckData.ProtoReflect.Descriptor instead.
func (*OrderCheckData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCheckData) GetMqlTradeCheckResult() *MrpcMqlTradeCheckResult {
	if x != nil {
		return x.MqlTradeCheckResult
	}
	return nil
}

type MrpcMqlTradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action                   MRPC_ENUM_TRADE_REQUEST_ACTIONS `protobuf:"varint,1,opt,name=action,proto3,enum=mt5_term_api.MRPC_ENUM_TRADE_REQUEST_ACTIONS" json:"action,omitempty"`                            // Trade operation type
	ExpertAdvisorMagicNumber uint64                          `protobuf:"varint,2,opt,name=expert_advisor_magic_number,json=expertAdvisorMagicNumber,proto3" json:"expert_advisor_magic_number,omitempty"`      // Expert Advisor ID (magic number)
	Order                    uint64                          `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`                                                                                // Order ticket
	Symbol                   string                          `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                                               // Symbol name
	Volume                   float64                         `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`                                                                             // Requested volume for a deal in lots
	Price                    float64                         `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`                                                                               // Price
	StopLimit                float64                         `protobuf:"fixed64,7,opt,name=stop_limit,json=stopLimit,proto3" json:"stop_limit,omitempty"`                                                      // StopLimit level of the order
	StopLoss                 float64                         `protobuf:"fixed64,8,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`                                                         // Stop Loss level of the order
	TakeProfit               float64                         `protobuf:"fixed64,9,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`                                                   // Take Profit level of the order
	Deviation                uint64                          `protobuf:"varint,10,opt,name=deviation,proto3" json:"deviation,omitempty"`                                                                       // Maximal possible deviation from the requested price
	OrderType                ENUM_ORDER_TYPE_TF              `protobuf:"varint,11,opt,name=order_type,json=orderType,proto3,enum=mt5_term_api.ENUM_ORDER_TYPE_TF" json:"order_type,omitempty"`                 // type of order
	TypeFilling              MRPC_ENUM_ORDER_TYPE_FILLING    `protobuf:"varint,12,opt,name=type_filling,json=typeFilling,proto3,enum=mt5_term_api.MRPC_ENUM_ORDER_TYPE_FILLING" json:"type_filling,omitempty"` // Order execution type
	TypeTime                 MRPC_ENUM_ORDER_TYPE_TIME       `protobuf:"varint,13,opt,name=type_time,json=typeTime,proto3,enum=mt5_term_api.MRPC_ENUM_ORDER_TYPE_TIME" json:"type_time,omitempty"`             // Order expiration type
	Expiration               *timestamppb.Timestamp          `protobuf:"bytes,14,opt,name=expiration,proto3" json:"expiration,omitempty"`                                                                      // Order expiration time (for the orders of ORDER_TIME_SPECIFIED type)
	Comment                  string                          `protobuf:"bytes,15,opt,name=comment,proto3" json:"comment,omitempty"`                                                                            // Order comment
	Position                 uint64                          `protobuf:"varint,16,opt,name=position,proto3" json:"position,omitempty"`                                                                         // Position ticket
	PositionBy               uint64                          `protobuf:"varint,17,opt,name=position_by,json=positionBy,proto3" json:"position_by,omitempty"`                                                   // The ticket of an opposite position
}

func (x *MrpcMqlTradeRequest) Reset() {
	*x = MrpcMqlTradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MrpcMqlTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MrpcMqlTradeRequest) ProtoMessage() {}

func (x *MrpcMqlTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MrpcMqlTradeRequest.ProtoReflect.Descriptor instead.
func (*MrpcMqlTradeRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{9}
}

func (x *MrpcMqlTradeRequest) GetAction() MRPC_ENUM_TRADE_REQUEST_ACTIONS {
	if x != nil {
		return x.Action
	}
	return MRPC_ENUM_TRADE_REQUEST_ACTIONS_TRADE_ACTION_DEAL
}

func (x *MrpcMqlTradeRequest) GetExpertAdvisorMagicNumber() uint64 {
	if x != nil {
		return x.ExpertAdvisorMagicNumber
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MrpcMqlTradeRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetStopLimit() float64 {
	if x != nil {
		return x.StopLimit
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetDeviation() uint64 {
	if x != nil {
		return x.Deviation
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetOrderType() ENUM_ORDER_TYPE_TF {
	if x != nil {
		return x.OrderType
	}
	return ENUM_ORDER_TYPE_TF_ORDER_TYPE_TF_BUY
}

func (x *MrpcMqlTradeRequest) GetTypeFilling() MRPC_ENUM_ORDER_TYPE_FILLING {
	if x != nil {
		return x.TypeFilling
	}
	return MRPC_ENUM_ORDER_TYPE_FILLING_ORDER_FILLING_FOK
}

func (x *MrpcMqlTradeRequest) GetTypeTime() MRPC_ENUM_ORDER_TYPE_TIME {
	if x != nil {
		return x.TypeTime
	}
	return MRPC_ENUM_ORDER_TYPE_TIME_ORDER_TIME_GTC
}

func (x *MrpcMqlTradeRequest) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *MrpcMqlTradeRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MrpcMqlTradeRequest) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MrpcMqlTradeRequest) GetPositionBy() uint64 {
	if x != nil {
		return x.PositionBy
	}
	return 0
}

type MrpcMqlTradeCheckResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnedCode     uint32  `protobuf:"varint,1,opt,name=returned_code,json=returnedCode,proto3" json:"returned_code,omitempty"`                // Reply code
	BalanceAfterDeal float64 `protobuf:"fixed64,2,opt,name=balance_after_deal,json=balanceAfterDeal,proto3" json:"balance_after_deal,omitempty"` // Balance after the execution of the deal
	EquityAfterDeal  float64 `protobuf:"fixed64,3,opt,name=equity_after_deal,json=equityAfterDeal,proto3" json:"equity_after_deal,omitempty"`    // Equity after the execution of the deal
	Profit           float64 `protobuf:"fixed64,4,opt,name=profit,proto3" json:"profit,omitempty"`                                               // Floating profit
	Margin           float64 `protobuf:"fixed64,5,opt,name=margin,proto3" json:"margin,omitempty"`                                               // Margin requirements
	FreeMargin       float64 `protobuf:"fixed64,6,opt,name=free_margin,json=freeMargin,proto3" json:"free_margin,omitempty"`                     // Free margin
	MarginLevel      float64 `protobuf:"fixed64,7,opt,name=margin_level,json=marginLevel,proto3" json:"margin_level,omitempty"`                  // Margin level
	Comment          string  `protobuf:"bytes,8,opt,name=comment,proto3" json:"comment,omitempty"`                                               // Comment to the reply code (description of the error)
}

func (x *MrpcMqlTradeCheckResult) Reset() {
	*x = MrpcMqlTradeCheckResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MrpcMqlTradeCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MrpcMqlTradeCheckResult) ProtoMessage() {}

func (x *MrpcMqlTradeCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MrpcMqlTradeCheckResult.ProtoReflect.Descriptor instead.
func (*MrpcMqlTradeCheckResult) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{10}
}

func (x *MrpcMqlTradeCheckResult) GetReturnedCode() uint32 {
	if x != nil {
		return x.ReturnedCode
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetBalanceAfterDeal() float64 {
	if x != nil {
		return x.BalanceAfterDeal
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetEquityAfterDeal() float64 {
	if x != nil {
		return x.EquityAfterDeal
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetMargin() float64 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetFreeMargin() float64 {
	if x != nil {
		return x.FreeMargin
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetMarginLevel() float64 {
	if x != nil {
		return x.MarginLevel
	}
	return 0
}

func (x *MrpcMqlTradeCheckResult) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// 6. PositionsTotal
type PositionsTotalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*PositionsTotalReply_Data
	//	*PositionsTotalReply_Error
	Response isPositionsTotalReply_Response `protobuf_oneof:"response"`
}

func (x *PositionsTotalReply) Reset() {
	*x = PositionsTotalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionsTotalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsTotalReply) ProtoMessage() {}

func (x *PositionsTotalReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsTotalReply.ProtoReflect.Descriptor instead.
func (*PositionsTotalReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{11}
}

func (m *PositionsTotalReply) GetResponse() isPositionsTotalReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PositionsTotalReply) GetData() *PositionsTotalData {
	if x, ok := x.GetResponse().(*PositionsTotalReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *PositionsTotalReply) GetError() *Error {
	if x, ok := x.GetResponse().(*PositionsTotalReply_Error); ok {
		return x.Error
	}
	return nil
}

type isPositionsTotalReply_Response interface {
	isPositionsTotalReply_Response()
}

type PositionsTotalReply_Data struct {
	Data *PositionsTotalData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type PositionsTotalReply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*PositionsTotalReply_Data) isPositionsTotalReply_Response() {}

func (*PositionsTotalReply_Error) isPositionsTotalReply_Response() {}

// Message to reply with the total number of positions
type PositionsTotalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total number of positions
	TotalPositions int32 `protobuf:"varint,1,opt,name=total_positions,json=totalPositions,proto3" json:"total_positions,omitempty"`
}

func (x *PositionsTotalData) Reset() {
	*x = PositionsTotalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_trade_functions_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionsTotalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsTotalData) ProtoMessage() {}

func (x *PositionsTotalData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_trade_functions_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsTotalData.ProtoReflect.Descriptor instead.
func (*PositionsTotalData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_trade_functions_proto_rawDescGZIP(), []int{12}
}

func (x *PositionsTotalData) GetTotalPositions() int32 {
	if x != nil {
		return x.TotalPositions
	}
	return 0
}

var File_mt5_term_api_trade_functions_proto protoreflect.FileDescriptor

var file_mt5_term_api_trade_functions_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x74, 0x35, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x2d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14,
	0x6d, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x74, 0x35, 0x2d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61,
	0x6c, 0x63, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x3f, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6d, 0x74,
	0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x4e, 0x55, 0x4d, 0x5f,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x52, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22,
	0x88, 0x01, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x4d, 0x61, 0x72,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x4d,
	0x61, 0x72, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x13, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x22, 0xc9, 0x01, 0x0a, 0x16, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d,
	0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2d, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x22,
	0x62, 0x0a, 0x11, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x11, 0x6d, 0x71, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x72, 0x70, 0x63, 0x4d, 0x71, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x0f, 0x6d, 0x71, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x7e, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x6c, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x5a, 0x0a, 0x16, 0x6d, 0x71, 0x6c, 0x5f, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x72, 0x70, 0x63, 0x4d, 0x71, 0x6c, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x13, 0x6d, 0x71,
	0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0xdb, 0x05, 0x0a, 0x13, 0x4d, 0x72, 0x70, 0x63, 0x4d, 0x71, 0x6c, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3d, 0x0a, 0x1b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x5f, 0x61, 0x64, 0x76, 0x69, 0x73,
	0x6f, 0x72, 0x5f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x18, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x41, 0x64, 0x76,
	0x69, 0x73, 0x6f, 0x72, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x73, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74,
	0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x73,
	0x74, 0x6f, 0x70, 0x4c, 0x6f, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x6b, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x61,
	0x6b, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x64, 0x65, 0x76,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6d, 0x74, 0x35,
	0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x66, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x52, 0x50,
	0x43, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x46, 0x49, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x52, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x46,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x44, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x49,
	0x4d, 0x45, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x79, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x22,
	0xa6, 0x02, 0x0a, 0x17, 0x4d, 0x72, 0x70, 0x63, 0x4d, 0x71, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x61, 0x66, 0x74, 0x65,
	0x72, 0x5f, 0x64, 0x65, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x2a,
	0x0a, 0x11, 0x65, 0x71, 0x75, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x64,
	0x65, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x65, 0x71, 0x75, 0x69, 0x74,
	0x79, 0x41, 0x66, 0x74, 0x65, 0x72, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72,
	0x65, 0x65, 0x5f, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x3d, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2a, 0x98, 0x02, 0x0a, 0x12, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x5f, 0x42, 0x55, 0x59, 0x10, 0x00, 0x12, 0x16,
	0x0a, 0x12, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x5f,
	0x53, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x5f, 0x42, 0x55, 0x59, 0x5f, 0x4c, 0x49, 0x4d, 0x49,
	0x54, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x54, 0x46, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10,
	0x03, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x54, 0x46, 0x5f, 0x42, 0x55, 0x59, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x04, 0x12, 0x1b, 0x0a,
	0x17, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x5f, 0x53,
	0x45, 0x4c, 0x4c, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x05, 0x12, 0x20, 0x0a, 0x1c, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x5f, 0x42, 0x55, 0x59, 0x5f,
	0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x06, 0x12, 0x21, 0x0a, 0x1d,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46, 0x5f, 0x53, 0x45,
	0x4c, 0x4c, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x07, 0x12,
	0x1a, 0x0a, 0x16, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x46,
	0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x42, 0x59, 0x10, 0x08, 0x2a, 0xb6, 0x01, 0x0a, 0x1f,
	0x4d, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x12,
	0x15, 0x0a, 0x11, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x44, 0x45, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x4c, 0x54, 0x50, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x52, 0x41, 0x44, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x59, 0x10, 0x03,
	0x12, 0x17, 0x0a, 0x13, 0x54, 0x52, 0x41, 0x44, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x52, 0x41,
	0x44, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f,
	0x42, 0x59, 0x10, 0x05, 0x2a, 0x7d, 0x0a, 0x1c, 0x4d, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x4e, 0x55,
	0x4d, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x4c,
	0x4c, 0x49, 0x4e, 0x47, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x49,
	0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x46, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x49, 0x4f, 0x43,
	0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x4c, 0x4c,
	0x49, 0x4e, 0x47, 0x5f, 0x42, 0x4f, 0x43, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x5f, 0x46, 0x49, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x54, 0x55, 0x52,
	0x4e, 0x10, 0x02, 0x2a, 0x7b, 0x0a, 0x19, 0x4d, 0x52, 0x50, 0x43, 0x5f, 0x45, 0x4e, 0x55, 0x4d,
	0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45,
	0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x47,
	0x54, 0x43, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x49,
	0x4d, 0x45, 0x5f, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45,
	0x5f, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x44, 0x41, 0x59, 0x10, 0x03,
	0x32, 0xc7, 0x03, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x75, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63,
	0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x4d,
	0x61, 0x72, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d,
	0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x61, 0x6c, 0x63, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x61, 0x6c, 0x63, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x75, 0x0a, 0x0f, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x12, 0x24, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12,
	0x10, 0x2f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x74, 0x12, 0x61, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x1f, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x64, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21,
	0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x42, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x2e, 0x6d, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2f,
	0x6d, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x6d,
	0x74, 0x35, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0xaa,
	0x02, 0x0c, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mt5_term_api_trade_functions_proto_rawDescOnce sync.Once
	file_mt5_term_api_trade_functions_proto_rawDescData = file_mt5_term_api_trade_functions_proto_rawDesc
)

func file_mt5_term_api_trade_functions_proto_rawDescGZIP() []byte {
	file_mt5_term_api_trade_functions_proto_rawDescOnce.Do(func() {
		file_mt5_term_api_trade_functions_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt5_term_api_trade_functions_proto_rawDescData)
	})
	return file_mt5_term_api_trade_functions_proto_rawDescData
}

var file_mt5_term_api_trade_functions_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mt5_term_api_trade_functions_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_mt5_term_api_trade_functions_proto_goTypes = []interface{}{
	(ENUM_ORDER_TYPE_TF)(0),              // 0: mt5_term_api.ENUM_ORDER_TYPE_TF
	(MRPC_ENUM_TRADE_REQUEST_ACTIONS)(0), // 1: mt5_term_api.MRPC_ENUM_TRADE_REQUEST_ACTIONS
	(MRPC_ENUM_ORDER_TYPE_FILLING)(0),    // 2: mt5_term_api.MRPC_ENUM_ORDER_TYPE_FILLING
	(MRPC_ENUM_ORDER_TYPE_TIME)(0),       // 3: mt5_term_api.MRPC_ENUM_ORDER_TYPE_TIME
	(*OrderCalcMarginRequest)(nil),       // 4: mt5_term_api.OrderCalcMarginRequest
	(*OrderCalcMarginReply)(nil),         // 5: mt5_term_api.OrderCalcMarginReply
	(*OrderCalcMarginData)(nil),          // 6: mt5_term_api.OrderCalcMarginData
	(*OrderCalcProfitRequest)(nil),       // 7: mt5_term_api.OrderCalcProfitRequest
	(*OrderCalcProfitReply)(nil),         // 8: mt5_term_api.OrderCalcProfitReply
	(*OrderCalcProfitData)(nil),          // 9: mt5_term_api.OrderCalcProfitData
	(*OrderCheckRequest)(nil),            // 10: mt5_term_api.OrderCheckRequest
	(*OrderCheckReply)(nil),              // 11: mt5_term_api.OrderCheckReply
	(*OrderCheckData)(nil),               // 12: mt5_term_api.OrderCheckData
	(*MrpcMqlTradeRequest)(nil),          // 13: mt5_term_api.MrpcMqlTradeRequest
	(*MrpcMqlTradeCheckResult)(nil),      // 14: mt5_term_api.MrpcMqlTradeCheckResult
	(*PositionsTotalReply)(nil),          // 15: mt5_term_api.PositionsTotalReply
	(*PositionsTotalData)(nil),           // 16: mt5_term_api.PositionsTotalData
	(*Error)(nil),                        // 17: mt5_term_api.Error
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 19: google.protobuf.Empty
}
var file_mt5_term_api_trade_functions_proto_depIdxs = []int32{
	0,  // 0: mt5_term_api.OrderCalcMarginRequest.order_type:type_name -> mt5_term_api.ENUM_ORDER_TYPE_TF
	6,  // 1: mt5_term_api.OrderCalcMarginReply.data:type_name -> mt5_term_api.OrderCalcMarginData
	17, // 2: mt5_term_api.OrderCalcMarginReply.error:type_name -> mt5_term_api.Error
	0,  // 3: mt5_term_api.OrderCalcProfitRequest.order_type:type_name -> mt5_term_api.ENUM_ORDER_TYPE_TF
	9,  // 4: mt5_term_api.OrderCalcProfitReply.data:type_name -> mt5_term_api.OrderCalcProfitData
	17, // 5: mt5_term_api.OrderCalcProfitReply.error:type_name -> mt5_term_api.Error
	13, // 6: mt5_term_api.OrderCheckRequest.mql_trade_request:type_name -> mt5_term_api.MrpcMqlTradeRequest
	12, // 7: mt5_term_api.OrderCheckReply.data:type_name -> mt5_term_api.OrderCheckData
	17, // 8: mt5_term_api.OrderCheckReply.error:type_name -> mt5_term_api.Error
	14, // 9: mt5_term_api.OrderCheckData.mql_trade_check_result:type_name -> mt5_term_api.MrpcMqlTradeCheckResult
	1,  // 10: mt5_term_api.MrpcMqlTradeRequest.action:type_name -> mt5_term_api.MRPC_ENUM_TRADE_REQUEST_ACTIONS
	0,  // 11: mt5_term_api.MrpcMqlTradeRequest.order_type:type_name -> mt5_term_api.ENUM_ORDER_TYPE_TF
	2,  // 12: mt5_term_api.MrpcMqlTradeRequest.type_filling:type_name -> mt5_term_api.MRPC_ENUM_ORDER_TYPE_FILLING
	3,  // 13: mt5_term_api.MrpcMqlTradeRequest.type_time:type_name -> mt5_term_api.MRPC_ENUM_ORDER_TYPE_TIME
	18, // 14: mt5_term_api.MrpcMqlTradeRequest.expiration:type_name -> google.protobuf.Timestamp
	16, // 15: mt5_term_api.PositionsTotalReply.data:type_name -> mt5_term_api.PositionsTotalData
	17, // 16: mt5_term_api.PositionsTotalReply.error:type_name -> mt5_term_api.Error
	4,  // 17: mt5_term_api.TradeFunctions.OrderCalcMargin:input_type -> mt5_term_api.OrderCalcMarginRequest
	7,  // 18: mt5_term_api.TradeFunctions.OrderCalcProfit:input_type -> mt5_term_api.OrderCalcProfitRequest
	10, // 19: mt5_term_api.TradeFunctions.OrderCheck:input_type -> mt5_term_api.OrderCheckRequest
	19, // 20: mt5_term_api.TradeFunctions.PositionsTotal:input_type -> google.protobuf.Empty
	5,  // 21: mt5_term_api.TradeFunctions.OrderCalcMargin:output_type -> mt5_term_api.OrderCalcMarginReply
	8,  // 22: mt5_term_api.TradeFunctions.OrderCalcProfit:output_type -> mt5_term_api.OrderCalcProfitReply
	11, // 23: mt5_term_api.TradeFunctions.OrderCheck:output_type -> mt5_term_api.OrderCheckReply
	15, // 24: mt5_term_api.TradeFunctions.PositionsTotal:output_type -> mt5_term_api.PositionsTotalReply
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_mt5_term_api_trade_functions_proto_init() }
func file_mt5_term_api_trade_functions_proto_init() {
	if File_mt5_term_api_trade_functions_proto != nil {
		return
	}
	file_mrpc_mt5_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mt5_term_api_trade_functions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCalcMarginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCalcMarginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCalcMarginData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCalcProfitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCalcProfitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCalcProfitData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCheckReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCheckData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MrpcMqlTradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MrpcMqlTradeCheckResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionsTotalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_trade_functions_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionsTotalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mt5_term_api_trade_functions_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OrderCalcMarginReply_Data)(nil),
		(*OrderCalcMarginReply_Error)(nil),
	}
	file_mt5_term_api_trade_functions_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*OrderCalcProfitReply_Data)(nil),
		(*OrderCalcProfitReply_Error)(nil),
	}
	file_mt5_term_api_trade_functions_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*OrderCheckReply_Data)(nil),
		(*OrderCheckReply_Error)(nil),
	}
	file_mt5_term_api_trade_functions_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*PositionsTotalReply_Data)(nil),
		(*PositionsTotalReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt5_term_api_trade_functions_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt5_term_api_trade_functions_proto_goTypes,
		DependencyIndexes: file_mt5_term_api_trade_functions_proto_depIdxs,
		EnumInfos:         file_mt5_term_api_trade_functions_proto_enumTypes,
		MessageInfos:      file_mt5_term_api_trade_functions_proto_msgTypes,
	}.Build()
	File_mt5_term_api_trade_functions_proto = out.File
	file_mt5_term_api_trade_functions_proto_rawDesc = nil
	file_mt5_term_api_trade_functions_proto_goTypes = nil
	file_mt5_term_api_trade_functions_proto_depIdxs = nil
}
