// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: mt5-term-api-gui.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuiLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GuiLoginRequest) Reset() {
	*x = GuiLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginRequest) ProtoMessage() {}

func (x *GuiLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginRequest.ProtoReflect.Descriptor instead.
func (*GuiLoginRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{0}
}

func (x *GuiLoginRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GuiLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GuiLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GuiLoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*GuiLoginReply_Data
	//	*GuiLoginReply_Error
	Response isGuiLoginReply_Response `protobuf_oneof:"response"`
}

func (x *GuiLoginReply) Reset() {
	*x = GuiLoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginReply) ProtoMessage() {}

func (x *GuiLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginReply.ProtoReflect.Descriptor instead.
func (*GuiLoginReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{1}
}

func (m *GuiLoginReply) GetResponse() isGuiLoginReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GuiLoginReply) GetData() *GuiLoginData {
	if x, ok := x.GetResponse().(*GuiLoginReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *GuiLoginReply) GetError() *GuiLoginError {
	if x, ok := x.GetResponse().(*GuiLoginReply_Error); ok {
		return x.Error
	}
	return nil
}

type isGuiLoginReply_Response interface {
	isGuiLoginReply_Response()
}

type GuiLoginReply_Data struct {
	Data *GuiLoginData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type GuiLoginReply_Error struct {
	Error *GuiLoginError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GuiLoginReply_Data) isGuiLoginReply_Response() {}

func (*GuiLoginReply_Error) isGuiLoginReply_Response() {}

type GuiLoginData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultCode int32  `protobuf:"varint,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	DebugLog   string `protobuf:"bytes,3,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
}

func (x *GuiLoginData) Reset() {
	*x = GuiLoginData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginData) ProtoMessage() {}

func (x *GuiLoginData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginData.ProtoReflect.Descriptor instead.
func (*GuiLoginData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{2}
}

func (x *GuiLoginData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GuiLoginData) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiLoginData) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

type GuiLoginError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GuiLoginError) Reset() {
	*x = GuiLoginError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginError) ProtoMessage() {}

func (x *GuiLoginError) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginError.ProtoReflect.Descriptor instead.
func (*GuiLoginError) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{3}
}

func (x *GuiLoginError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GuiBrokerSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchText     string `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	TimeoutSeconds int32  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WaitResult     bool   `protobuf:"varint,3,opt,name=wait_result,json=waitResult,proto3" json:"wait_result,omitempty"`
}

func (x *GuiBrokerSearchRequest) Reset() {
	*x = GuiBrokerSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiBrokerSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiBrokerSearchRequest) ProtoMessage() {}

func (x *GuiBrokerSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiBrokerSearchRequest.ProtoReflect.Descriptor instead.
func (*GuiBrokerSearchRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{4}
}

func (x *GuiBrokerSearchRequest) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *GuiBrokerSearchRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *GuiBrokerSearchRequest) GetWaitResult() bool {
	if x != nil {
		return x.WaitResult
	}
	return false
}

type GuiBrokerSearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*GuiBrokerSearchReply_Data
	//	*GuiBrokerSearchReply_Error
	Response isGuiBrokerSearchReply_Response `protobuf_oneof:"response"`
}

func (x *GuiBrokerSearchReply) Reset() {
	*x = GuiBrokerSearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiBrokerSearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiBrokerSearchReply) ProtoMessage() {}

func (x *GuiBrokerSearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiBrokerSearchReply.ProtoReflect.Descriptor instead.
func (*GuiBrokerSearchReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{5}
}

func (m *GuiBrokerSearchReply) GetResponse() isGuiBrokerSearchReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GuiBrokerSearchReply) GetData() *GuiBrokerSearchData {
	if x, ok := x.GetResponse().(*GuiBrokerSearchReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *GuiBrokerSearchReply) GetError() *GuiBrokerSearchError {
	if x, ok := x.GetResponse().(*GuiBrokerSearchReply_Error); ok {
		return x.Error
	}
	return nil
}

type isGuiBrokerSearchReply_Response interface {
	isGuiBrokerSearchReply_Response()
}

type GuiBrokerSearchReply_Data struct {
	Data *GuiBrokerSearchData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type GuiBrokerSearchReply_Error struct {
	Error *GuiBrokerSearchError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GuiBrokerSearchReply_Data) isGuiBrokerSearchReply_Response() {}

func (*GuiBrokerSearchReply_Error) isGuiBrokerSearchReply_Response() {}

type GuiBrokerSearchData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode int32    `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Brokers    []string `protobuf:"bytes,2,rep,name=brokers,proto3" json:"brokers,omitempty"`
	DebugLog   string   `protobuf:"bytes,3,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
}

func (x *GuiBrokerSearchData) Reset() {
	*x = GuiBrokerSearchData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiBrokerSearchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiBrokerSearchData) ProtoMessage() {}

func (x *GuiBrokerSearchData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiBrokerSearchData.ProtoReflect.Descriptor instead.
func (*GuiBrokerSearchData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{6}
}

func (x *GuiBrokerSearchData) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiBrokerSearchData) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *GuiBrokerSearchData) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

type GuiBrokerSearchError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GuiBrokerSearchError) Reset() {
	*x = GuiBrokerSearchError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiBrokerSearchError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiBrokerSearchError) ProtoMessage() {}

func (x *GuiBrokerSearchError) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiBrokerSearchError.ProtoReflect.Descriptor instead.
func (*GuiBrokerSearchError) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{7}
}

func (x *GuiBrokerSearchError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GuiLoginExRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GuiLoginExRequest) Reset() {
	*x = GuiLoginExRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginExRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginExRequest) ProtoMessage() {}

func (x *GuiLoginExRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginExRequest.ProtoReflect.Descriptor instead.
func (*GuiLoginExRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{8}
}

func (x *GuiLoginExRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GuiLoginExRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GuiLoginExRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GuiLoginExReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*GuiLoginExReply_Data
	//	*GuiLoginExReply_Error
	Response isGuiLoginExReply_Response `protobuf_oneof:"response"`
}

func (x *GuiLoginExReply) Reset() {
	*x = GuiLoginExReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginExReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginExReply) ProtoMessage() {}

func (x *GuiLoginExReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginExReply.ProtoReflect.Descriptor instead.
func (*GuiLoginExReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{9}
}

func (m *GuiLoginExReply) GetResponse() isGuiLoginExReply_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GuiLoginExReply) GetData() *GuiLoginExData {
	if x, ok := x.GetResponse().(*GuiLoginExReply_Data); ok {
		return x.Data
	}
	return nil
}

func (x *GuiLoginExReply) GetError() *GuiLoginExError {
	if x, ok := x.GetResponse().(*GuiLoginExReply_Error); ok {
		return x.Error
	}
	return nil
}

type isGuiLoginExReply_Response interface {
	isGuiLoginExReply_Response()
}

type GuiLoginExReply_Data struct {
	Data *GuiLoginExData `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type GuiLoginExReply_Error struct {
	Error *GuiLoginExError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GuiLoginExReply_Data) isGuiLoginExReply_Response() {}

func (*GuiLoginExReply_Error) isGuiLoginExReply_Response() {}

type GuiLoginExData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success          bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultCode       int32    `protobuf:"varint,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	AvailableServers []string `protobuf:"bytes,3,rep,name=available_servers,json=availableServers,proto3" json:"available_servers,omitempty"`
	DebugLog         string   `protobuf:"bytes,4,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
}

func (x *GuiLoginExData) Reset() {
	*x = GuiLoginExData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginExData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginExData) ProtoMessage() {}

func (x *GuiLoginExData) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginExData.ProtoReflect.Descriptor instead.
func (*GuiLoginExData) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{10}
}

func (x *GuiLoginExData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GuiLoginExData) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiLoginExData) GetAvailableServers() []string {
	if x != nil {
		return x.AvailableServers
	}
	return nil
}

func (x *GuiLoginExData) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

type GuiLoginExError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GuiLoginExError) Reset() {
	*x = GuiLoginExError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiLoginExError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiLoginExError) ProtoMessage() {}

func (x *GuiLoginExError) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiLoginExError.ProtoReflect.Descriptor instead.
func (*GuiLoginExError) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{11}
}

func (x *GuiLoginExError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GuiCloseDialogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuiCloseDialogsRequest) Reset() {
	*x = GuiCloseDialogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiCloseDialogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiCloseDialogsRequest) ProtoMessage() {}

func (x *GuiCloseDialogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiCloseDialogsRequest.ProtoReflect.Descriptor instead.
func (*GuiCloseDialogsRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{12}
}

type GuiCloseDialogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClosedCount int32 `protobuf:"varint,1,opt,name=closed_count,json=closedCount,proto3" json:"closed_count,omitempty"`
}

func (x *GuiCloseDialogsReply) Reset() {
	*x = GuiCloseDialogsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiCloseDialogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiCloseDialogsReply) ProtoMessage() {}

func (x *GuiCloseDialogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiCloseDialogsReply.ProtoReflect.Descriptor instead.
func (*GuiCloseDialogsReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{13}
}

func (x *GuiCloseDialogsReply) GetClosedCount() int32 {
	if x != nil {
		return x.ClosedCount
	}
	return 0
}

type GuiDemoFindCompaniesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchText     string `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	TimeoutSeconds int32  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *GuiDemoFindCompaniesRequest) Reset() {
	*x = GuiDemoFindCompaniesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoFindCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoFindCompaniesRequest) ProtoMessage() {}

func (x *GuiDemoFindCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoFindCompaniesRequest.ProtoReflect.Descriptor instead.
func (*GuiDemoFindCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{14}
}

func (x *GuiDemoFindCompaniesRequest) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *GuiDemoFindCompaniesRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GuiDemoFindCompaniesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode int32             `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Companies  []*GuiDemoCompany `protobuf:"bytes,2,rep,name=companies,proto3" json:"companies,omitempty"`
	DebugLog   string            `protobuf:"bytes,3,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
}

func (x *GuiDemoFindCompaniesReply) Reset() {
	*x = GuiDemoFindCompaniesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoFindCompaniesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoFindCompaniesReply) ProtoMessage() {}

func (x *GuiDemoFindCompaniesReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoFindCompaniesReply.ProtoReflect.Descriptor instead.
func (*GuiDemoFindCompaniesReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{15}
}

func (x *GuiDemoFindCompaniesReply) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiDemoFindCompaniesReply) GetCompanies() []*GuiDemoCompany {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *GuiDemoFindCompaniesReply) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

type GuiDemoCompany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
}

func (x *GuiDemoCompany) Reset() {
	*x = GuiDemoCompany{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoCompany) ProtoMessage() {}

func (x *GuiDemoCompany) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoCompany.ProtoReflect.Descriptor instead.
func (*GuiDemoCompany) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{16}
}

func (x *GuiDemoCompany) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuiDemoCompany) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

type GuiDemoServersAndTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyName    string `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	TimeoutSeconds int32  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *GuiDemoServersAndTypesRequest) Reset() {
	*x = GuiDemoServersAndTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoServersAndTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoServersAndTypesRequest) ProtoMessage() {}

func (x *GuiDemoServersAndTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoServersAndTypesRequest.ProtoReflect.Descriptor instead.
func (*GuiDemoServersAndTypesRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{17}
}

func (x *GuiDemoServersAndTypesRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GuiDemoServersAndTypesRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GuiDemoServersAndTypesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode   int32    `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Servers      []string `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	AccountTypes []string `protobuf:"bytes,3,rep,name=account_types,json=accountTypes,proto3" json:"account_types,omitempty"`
	Deposits     []string `protobuf:"bytes,4,rep,name=deposits,proto3" json:"deposits,omitempty"`
	Leverages    []string `protobuf:"bytes,5,rep,name=leverages,proto3" json:"leverages,omitempty"`
	DebugLog     string   `protobuf:"bytes,6,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
}

func (x *GuiDemoServersAndTypesReply) Reset() {
	*x = GuiDemoServersAndTypesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoServersAndTypesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoServersAndTypesReply) ProtoMessage() {}

func (x *GuiDemoServersAndTypesReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoServersAndTypesReply.ProtoReflect.Descriptor instead.
func (*GuiDemoServersAndTypesReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{18}
}

func (x *GuiDemoServersAndTypesReply) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiDemoServersAndTypesReply) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *GuiDemoServersAndTypesReply) GetAccountTypes() []string {
	if x != nil {
		return x.AccountTypes
	}
	return nil
}

func (x *GuiDemoServersAndTypesReply) GetDeposits() []string {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *GuiDemoServersAndTypesReply) GetLeverages() []string {
	if x != nil {
		return x.Leverages
	}
	return nil
}

func (x *GuiDemoServersAndTypesReply) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

type GuiDemoOpenAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company        string `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	FirstName      string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email          string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Server         string `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	AccountType    string `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	TimeoutSeconds int32  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *GuiDemoOpenAccountRequest) Reset() {
	*x = GuiDemoOpenAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoOpenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoOpenAccountRequest) ProtoMessage() {}

func (x *GuiDemoOpenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoOpenAccountRequest.ProtoReflect.Descriptor instead.
func (*GuiDemoOpenAccountRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{19}
}

func (x *GuiDemoOpenAccountRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *GuiDemoOpenAccountRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GuiDemoOpenAccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode int32  `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Login      string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Investor   string `protobuf:"bytes,4,opt,name=investor,proto3" json:"investor,omitempty"`
	Server     string `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	DebugLog   string `protobuf:"bytes,6,opt,name=debug_log,json=debugLog,proto3" json:"debug_log,omitempty"`
}

func (x *GuiDemoOpenAccountReply) Reset() {
	*x = GuiDemoOpenAccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoOpenAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoOpenAccountReply) ProtoMessage() {}

func (x *GuiDemoOpenAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoOpenAccountReply.ProtoReflect.Descriptor instead.
func (*GuiDemoOpenAccountReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{20}
}

func (x *GuiDemoOpenAccountReply) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *GuiDemoOpenAccountReply) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetInvestor() string {
	if x != nil {
		return x.Investor
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GuiDemoOpenAccountReply) GetDebugLog() string {
	if x != nil {
		return x.DebugLog
	}
	return ""
}

type GuiDemoEnumControlsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GuiDemoEnumControlsRequest) Reset() {
	*x = GuiDemoEnumControlsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoEnumControlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoEnumControlsRequest) ProtoMessage() {}

func (x *GuiDemoEnumControlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoEnumControlsRequest.ProtoReflect.Descriptor instead.
func (*GuiDemoEnumControlsRequest) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{21}
}

type GuiDemoEnumControlsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControlCount int32  `protobuf:"varint,1,opt,name=control_count,json=controlCount,proto3" json:"control_count,omitempty"`
	ControlsDump string `protobuf:"bytes,2,opt,name=controls_dump,json=controlsDump,proto3" json:"controls_dump,omitempty"`
}

func (x *GuiDemoEnumControlsReply) Reset() {
	*x = GuiDemoEnumControlsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoEnumControlsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoEnumControlsReply) ProtoMessage() {}

func (x *GuiDemoEnumControlsReply) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoEnumControlsReply.ProtoReflect.Descriptor instead.
func (*GuiDemoEnumControlsReply) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{22}
}

func (x *GuiDemoEnumControlsReply) GetControlCount() int32 {
	if x != nil {
		return x.ControlCount
	}
	return 0
}

func (x *GuiDemoEnumControlsReply) GetControlsDump() string {
	if x != nil {
		return x.ControlsDump
	}
	return ""
}

type GuiDemoProgressEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step        string                   `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Message     string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ElapsedMs   int64                    `protobuf:"varint,3,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	IsFinal     bool                     `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	AccountData *GuiDemoOpenAccountReply `protobuf:"bytes,5,opt,name=account_data,json=accountData,proto3" json:"account_data,omitempty"`
	ErrorCode   int32                    `protobuf:"varint,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *GuiDemoProgressEvent) Reset() {
	*x = GuiDemoProgressEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mt5_term_api_gui_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuiDemoProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiDemoProgressEvent) ProtoMessage() {}

func (x *GuiDemoProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mt5_term_api_gui_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiDemoProgressEvent.ProtoReflect.Descriptor instead.
func (*GuiDemoProgressEvent) Descriptor() ([]byte, []int) {
	return file_mt5_term_api_gui_proto_rawDescGZIP(), []int{23}
}

func (x *GuiDemoProgressEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *GuiDemoProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GuiDemoProgressEvent) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *GuiDemoProgressEvent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *GuiDemoProgressEvent) GetAccountData() *GuiDemoOpenAccountReply {
	if x != nil {
		return x.AccountData
	}
	return nil
}

func (x *GuiDemoProgressEvent) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_mt5_term_api_gui_proto protoreflect.FileDescriptor

var file_mt5_term_api_gui_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x74, 0x35, 0x2d, 0x74, 0x65, 0x72, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67,
	0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x5b, 0x0a, 0x0f, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x33, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x66, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6c, 0x6f, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67,
	0x22, 0x34, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x16, 0x47, 0x75, 0x69, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77,
	0x61, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x77, 0x61, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x97, 0x01, 0x0a,
	0x14, 0x47, 0x75, 0x69, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3a,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d, 0x0a, 0x13, 0x47, 0x75, 0x69, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x4c, 0x6f, 0x67, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x75, 0x69, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x5d, 0x0a, 0x11, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x88, 0x01, 0x0a, 0x0f, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x45, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x95, 0x01, 0x0a,
	0x0e, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x62, 0x75,
	0x67, 0x4c, 0x6f, 0x67, 0x22, 0x36, 0x0a, 0x0f, 0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x45, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16,
	0x47, 0x75, 0x69, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x14, 0x47, 0x75, 0x69, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x67, 0x0a, 0x1b, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x69, 0x6e, 0x64,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x19, 0x47,
	0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d,
	0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44,
	0x65, 0x6d, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6c,
	0x6f, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x62, 0x75, 0x67, 0x4c,
	0x6f, 0x67, 0x22, 0x43, 0x0a, 0x0e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6b, 0x0a, 0x1d, 0x47, 0x75, 0x69, 0x44, 0x65,
	0x6d, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x1b, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67, 0x22, 0x81, 0x02, 0x0a, 0x19,
	0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22,
	0xbd, 0x01, 0x0a, 0x17, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6c, 0x6f, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67, 0x22,
	0x1c, 0x0a, 0x1a, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x64, 0x0a,
	0x18, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x44,
	0x75, 0x6d, 0x70, 0x22, 0xe7, 0x01, 0x0a, 0x14, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6c,
	0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x4d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x12, 0x48, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x74, 0x35,
	0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d,
	0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x32, 0xd8, 0x06,
	0x0a, 0x03, 0x47, 0x75, 0x69, 0x12, 0x43, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1d,
	0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75,
	0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x58, 0x0a, 0x0c, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x24, 0x2e, 0x6d, 0x74, 0x35,
	0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x75, 0x69, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78, 0x12,
	0x1f, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x75, 0x69, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x58, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x12,
	0x24, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x75, 0x69, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x67, 0x0a, 0x11, 0x44, 0x65, 0x6d,
	0x6f, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x73, 0x12, 0x29,
	0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75,
	0x69, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f,
	0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x6d, 0x0a, 0x13, 0x44, 0x65, 0x6d, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x41, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x2b, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72,
	0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x61, 0x0a, 0x0f, 0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69,
	0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x64, 0x0a, 0x10, 0x44, 0x65, 0x6d, 0x6f, 0x45, 0x6e, 0x75, 0x6d,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x12, 0x28, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x45,
	0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6c, 0x0a, 0x1b, 0x44, 0x65,
	0x6d, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x27, 0x2e, 0x6d, 0x74, 0x35, 0x5f,
	0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f,
	0x4f, 0x70, 0x65, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x75, 0x69, 0x44, 0x65, 0x6d, 0x6f, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x42, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x2e,
	0x6d, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x6d, 0x72,
	0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x6d, 0x74, 0x35,
	0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0xaa, 0x02, 0x0c,
	0x6d, 0x74, 0x35, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mt5_term_api_gui_proto_rawDescOnce sync.Once
	file_mt5_term_api_gui_proto_rawDescData = file_mt5_term_api_gui_proto_rawDesc
)

func file_mt5_term_api_gui_proto_rawDescGZIP() []byte {
	file_mt5_term_api_gui_proto_rawDescOnce.Do(func() {
		file_mt5_term_api_gui_proto_rawDescData = protoimpl.X.CompressGZIP(file_mt5_term_api_gui_proto_rawDescData)
	})
	return file_mt5_term_api_gui_proto_rawDescData
}

var file_mt5_term_api_gui_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_mt5_term_api_gui_proto_goTypes = []interface{}{
	(*GuiLoginRequest)(nil),               // 0: mt5_term_api.GuiLoginRequest
	(*GuiLoginReply)(nil),                 // 1: mt5_term_api.GuiLoginReply
	(*GuiLoginData)(nil),                  // 2: mt5_term_api.GuiLoginData
	(*GuiLoginError)(nil),                 // 3: mt5_term_api.GuiLoginError
	(*GuiBrokerSearchRequest)(nil),        // 4: mt5_term_api.GuiBrokerSearchRequest
	(*GuiBrokerSearchReply)(nil),          // 5: mt5_term_api.GuiBrokerSearchReply
	(*GuiBrokerSearchData)(nil),           // 6: mt5_term_api.GuiBrokerSearchData
	(*GuiBrokerSearchError)(nil),          // 7: mt5_term_api.GuiBrokerSearchError
	(*GuiLoginExRequest)(nil),             // 8: mt5_term_api.GuiLoginExRequest
	(*GuiLoginExReply)(nil),               // 9: mt5_term_api.GuiLoginExReply
	(*GuiLoginExData)(nil),                // 10: mt5_term_api.GuiLoginExData
	(*GuiLoginExError)(nil),               // 11: mt5_term_api.GuiLoginExError
	(*GuiCloseDialogsRequest)(nil),        // 12: mt5_term_api.GuiCloseDialogsRequest
	(*GuiCloseDialogsReply)(nil),          // 13: mt5_term_api.GuiCloseDialogsReply
	(*GuiDemoFindCompaniesRequest)(nil),   // 14: mt5_term_api.GuiDemoFindCompaniesRequest
	(*GuiDemoFindCompaniesReply)(nil),     // 15: mt5_term_api.GuiDemoFindCompaniesReply
	(*GuiDemoCompany)(nil),                // 16: mt5_term_api.GuiDemoCompany
	(*GuiDemoServersAndTypesRequest)(nil), // 17: mt5_term_api.GuiDemoServersAndTypesRequest
	(*GuiDemoServersAndTypesReply)(nil),   // 18: mt5_term_api.GuiDemoServersAndTypesReply
	(*GuiDemoOpenAccountRequest)(nil),     // 19: mt5_term_api.GuiDemoOpenAccountRequest
	(*GuiDemoOpenAccountReply)(nil),       // 20: mt5_term_api.GuiDemoOpenAccountReply
	(*GuiDemoEnumControlsRequest)(nil),    // 21: mt5_term_api.GuiDemoEnumControlsRequest
	(*GuiDemoEnumControlsReply)(nil),      // 22: mt5_term_api.GuiDemoEnumControlsReply
	(*GuiDemoProgressEvent)(nil),          // 23: mt5_term_api.GuiDemoProgressEvent
}
var file_mt5_term_api_gui_proto_depIdxs = []int32{
	2,  // 0: mt5_term_api.GuiLoginReply.data:type_name -> mt5_term_api.GuiLoginData
	3,  // 1: mt5_term_api.GuiLoginReply.error:type_name -> mt5_term_api.GuiLoginError
	6,  // 2: mt5_term_api.GuiBrokerSearchReply.data:type_name -> mt5_term_api.GuiBrokerSearchData
	7,  // 3: mt5_term_api.GuiBrokerSearchReply.error:type_name -> mt5_term_api.GuiBrokerSearchError
	10, // 4: mt5_term_api.GuiLoginExReply.data:type_name -> mt5_term_api.GuiLoginExData
	11, // 5: mt5_term_api.GuiLoginExReply.error:type_name -> mt5_term_api.GuiLoginExError
	16, // 6: mt5_term_api.GuiDemoFindCompaniesReply.companies:type_name -> mt5_term_api.GuiDemoCompany
	20, // 7: mt5_term_api.GuiDemoProgressEvent.account_data:type_name -> mt5_term_api.GuiDemoOpenAccountReply
	0,  // 8: mt5_term_api.Gui.Login:input_type -> mt5_term_api.GuiLoginRequest
	4,  // 9: mt5_term_api.Gui.BrokerSearch:input_type -> mt5_term_api.GuiBrokerSearchRequest
	8,  // 10: mt5_term_api.Gui.LoginEx:input_type -> mt5_term_api.GuiLoginExRequest
	12, // 11: mt5_term_api.Gui.CloseDialogs:input_type -> mt5_term_api.GuiCloseDialogsRequest
	14, // 12: mt5_term_api.Gui.DemoFindCompanies:input_type -> mt5_term_api.GuiDemoFindCompaniesRequest
	17, // 13: mt5_term_api.Gui.DemoServersAndTypes:input_type -> mt5_term_api.GuiDemoServersAndTypesRequest
	19, // 14: mt5_term_api.Gui.DemoOpenAccount:input_type -> mt5_term_api.GuiDemoOpenAccountRequest
	21, // 15: mt5_term_api.Gui.DemoEnumControls:input_type -> mt5_term_api.GuiDemoEnumControlsRequest
	19, // 16: mt5_term_api.Gui.DemoOpenAccountWithProgress:input_type -> mt5_term_api.GuiDemoOpenAccountRequest
	1,  // 17: mt5_term_api.Gui.Login:output_type -> mt5_term_api.GuiLoginReply
	5,  // 18: mt5_term_api.Gui.BrokerSearch:output_type -> mt5_term_api.GuiBrokerSearchReply
	9,  // 19: mt5_term_api.Gui.LoginEx:output_type -> mt5_term_api.GuiLoginExReply
	13, // 20: mt5_term_api.Gui.CloseDialogs:output_type -> mt5_term_api.GuiCloseDialogsReply
	15, // 21: mt5_term_api.Gui.DemoFindCompanies:output_type -> mt5_term_api.GuiDemoFindCompaniesReply
	18, // 22: mt5_term_api.Gui.DemoServersAndTypes:output_type -> mt5_term_api.GuiDemoServersAndTypesReply
	20, // 23: mt5_term_api.Gui.DemoOpenAccount:output_type -> mt5_term_api.GuiDemoOpenAccountReply
	22, // 24: mt5_term_api.Gui.DemoEnumControls:output_type -> mt5_term_api.GuiDemoEnumControlsReply
	23, // 25: mt5_term_api.Gui.DemoOpenAccountWithProgress:output_type -> mt5_term_api.GuiDemoProgressEvent
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mt5_term_api_gui_proto_init() }
func file_mt5_term_api_gui_proto_init() {
	if File_mt5_term_api_gui_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mt5_term_api_gui_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiBrokerSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiBrokerSearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiBrokerSearchData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiBrokerSearchError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginExRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginExReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginExData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiLoginExError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiCloseDialogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiCloseDialogsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoFindCompaniesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoFindCompaniesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoCompany); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoServersAndTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoServersAndTypesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoOpenAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoOpenAccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoEnumControlsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoEnumControlsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mt5_term_api_gui_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuiDemoProgressEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mt5_term_api_gui_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GuiLoginReply_Data)(nil),
		(*GuiLoginReply_Error)(nil),
	}
	file_mt5_term_api_gui_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*GuiBrokerSearchReply_Data)(nil),
		(*GuiBrokerSearchReply_Error)(nil),
	}
	file_mt5_term_api_gui_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*GuiLoginExReply_Data)(nil),
		(*GuiLoginExReply_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mt5_term_api_gui_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mt5_term_api_gui_proto_goTypes,
		DependencyIndexes: file_mt5_term_api_gui_proto_depIdxs,
		MessageInfos:      file_mt5_term_api_gui_proto_msgTypes,
	}.Build()
	File_mt5_term_api_gui_proto = out.File
	file_mt5_term_api_gui_proto_rawDesc = nil
	file_mt5_term_api_gui_proto_goTypes = nil
	file_mt5_term_api_gui_proto_depIdxs = nil
}
